// Prepared for user execution. No world assets or long simulations.
const {test,expect}=require('@playwright/test'),{Simulation,ordinal,validateGameState}=require('../shared/simulation.cjs'),{EconomyPool}=require('../shared/economy-pool.cjs'),{Worker}=require('node:worker_threads'),path=require('node:path'),fixture=require('./fixtures/household-integration.cjs');
function create(options={}){const data=fixture.createScenario(options),s=new Simulation(data.scenario,data.hierarchy,{seed:1700,landAdjacency:data.adjacency});s.enableAutonomy({birthRateBps:0,deathRateBps:0,foodFeedback:true});return {s,...data};}
function days(s){const d=s.clock.date;return ordinal({year:d.year+(d.month===12?1:0),month:d.month===12?1:d.month+1,day:1})-ordinal(d);}
function month(s){s.step(days(s));return s.snapshot().systems.economy;}
const own=e=>e.householdEconomy.rows.find(r=>r.householdId==='household-local');
const stock=(row,id)=>row.inventories.find(s=>s.goodId===id);
test('household food traverses physical recipes over three months without startup goods',()=>{const {s}=create({buyer:false});const a=month(s);expect(own(a).ledger.find(b=>b.goodId==='grain').produced).toBeGreaterThan(0);expect(stock(own(a),'food').quantity).toBe(0);const b=month(s);expect(own(b).ledger.find(b=>b.goodId==='grain').inputs).toBeGreaterThan(0);expect(stock(own(b),'food').quantity).toBe(0);const c=month(s);expect(own(c).ledger.find(b=>b.goodId==='flour').inputs).toBeGreaterThan(0);expect(s.economicReport().naturalFoodConsumed).toBeGreaterThan(0);});
test('no labor produces no household goods',()=>{const {s}=create(),v=s.snapshot();v.systems.economy.rules.laborParticipationBps=0;s.load(v);const e=month(s);expect(own(e).workers).toBe(0);expect(own(e).inventories.every(s=>!s.quantity)).toBe(true);});
test('urban households have no implicit agricultural capacity',()=>{const {s}=create();for(let i=0;i<3;i++)month(s);const row=s.economySummary().householdEconomy.rows.find(r=>r.householdId==='household-neighbor');expect(row.stages.every(s=>s.capacityBatches===0)).toBe(true);expect(row.workers).toBe(0);});
test('formal payroll and household workshops use one labor pool',()=>{const {s}=create(),v=s.snapshot(),e=v.systems.economy;e.rules.foodGoodId='grain';e.rules.consumerNeeds[0].goodId='grain';e.rules.consumerNeeds[0].perPersonDenominator=1;e.households[0].cashMinor=100000;const r=e.recipes.find(r=>r.id==='grow-grain');e.enterprises.push({id:'labor-employer',provinceId:'province:00001',ownerRef:{kind:'household',id:e.households[0].id},recipeId:r.id,capacityBatches:500,wagePerWorkerMinor:1,cashMinor:100000,inventories:e.goods.map(g=>({goodId:g.id,quantity:0,bookValueMinor:0})),stats:{batches:0,workers:0,wages:0,inputsConsumedValue:0,productionCost:0,inputPurchases:0,revenue:0,cogs:0,profit:0,payout:0}});e.autonomy.firms.push(require('../shared/autonomous-economy.cjs').record(e.enterprises[0]));v.systems.settlements.placements.push({enterpriseId:'labor-employer',settlementId:v.systems.settlements.rows.find(r=>r.provinceId==='province:00001').id,kind:'settlement'});delete e.householdEconomy;delete e.agriculture;s.load(v);const next=month(s),paid=next.enterprises.reduce((n,f)=>n+f.stats.workers,0);expect(paid+own(next).workers).toBeLessThanOrEqual(500);expect(paid).toBeGreaterThan(0);});
test('food consumption and surplus sale debit distinct physical quantities',()=>{const {s}=create();for(let i=0;i<3;i++)month(s);const e=s.economySummary(),b=own(e).ledger.find(b=>b.goodId==='food');expect(b.consumed).toBeGreaterThan(0);expect(b.sold).toBeGreaterThan(0);expect(b.consumed+b.sold+b.closing).toBe(b.opening+b.produced+b.bought-b.inputs);expect(own(e).revenue).toBeGreaterThan(0);});
test('natural plus paid food equals total consumed and feeds the existing deficit history',()=>{const {s}=create({buyer:false});for(let i=0;i<4;i++)month(s);const r=s.economicReport(),e=s.economySummary();expect(r.naturalFoodConsumed+r.marketFoodConsumed).toBe(r.goods.food.householdConsumed);expect(e.autonomy.foodSecurity.households.find(h=>h.householdId==='household-local').deficitMonths).toBeLessThan(4);});
test('household sales, payroll, dividends and freight conserve all cash including escrow',()=>{for(const trade of [false,true]){const {s,hierarchy}=create({trade}),cash=s.economicReport().cash;for(let i=0;i<4;i++){month(s);expect(s.economicReport().cash).toBe(cash);validateGameState(s.snapshot(),hierarchy);}}});
test('two-edge cargo has an owner and stops at the intermediate market',()=>{const {s}=create({trade:true}),e=month(s),r=e.trade.routing;expect(r.cargo).toHaveLength(1);const c=r.cargo[0];expect(c.ownerId).toBe('household-far');expect(c.path).toHaveLength(3);expect(c.index).toBe(1);expect(c.escrowMinor).toBeGreaterThan(0);expect(e.trade.householdStocks.find(h=>h.householdId===c.ownerId).quantity).toBe(0);expect(month(s).trade.routing.cargo).toHaveLength(0);expect(s.economySummary().trade.householdStocks.find(h=>h.householdId==='household-far').quantity).toBeGreaterThan(0);});
test('a stalled shipment is neither duplicated nor lost and pays no idle freight',()=>{const {s}=create({trade:true});month(s);const v=s.snapshot();v.systems.economy.rules.laborParticipationBps=0;s.load(v);const before=s.economicReport().cash,cargo=s.economySummary().trade.routing.cargo;const e=month(s);expect(e.trade.routing.cargo).toEqual(cargo);expect(e.trade.routing.month.freight).toBe(0);expect(s.economicReport().cash).toBe(before);});
test('transport workers receive actual money on each traversed edge',()=>{const {s}=create({trade:true});const first=month(s);expect(first.households.find(h=>h.id==='household-local').stats.wages).toBe(8);const second=month(s);expect(second.households.find(h=>h.id==='household-neighbor').stats.wages).toBe(8);expect(second.trade.routing.month.byProvince['province:00002'].freight).toBe(8);});
test('routes that cost more than destination quotes do not create shipments',()=>{const {s}=create({trade:true}),v=s.snapshot();for(const m of v.systems.economy.markets)m.goods.find(g=>g.goodId==='food').priceMinor=1;s.load(v);const e=month(s);expect(e.trade.routing.cargo).toEqual([]);expect(e.trade.routing.month.started).toBe(0);expect(e.trade.routing.month.rejected.price).toBeGreaterThan(0);});
test('partial funded maintenance consumes only installed equipment and retains the remainder',()=>{const {s}=create({trade:true}),v=s.snapshot(),e=v.systems.economy,f=e.enterprises[0],c=e.autonomy.firms[0];c.pendingCapacity=10;c.replacementCapacity=10;stock(f,'tools').quantity=1;stock(f,'tools').bookValueMinor=10;s.load(v);const next=month(s),control=next.autonomy.firms[0];expect(control.capitalInUse.quantity).toBe(1);expect(control.pendingCapacity).toBe(9);expect(control.replacementCapacity).toBe(9);expect(next.autonomy.events.maintenance).toBeGreaterThan(0);});
test('a maintenance request cannot manufacture tools when none exist',()=>{const {s}=create({trade:true}),v=s.snapshot();v.systems.economy.autonomy.firms[0].pendingCapacity=3;s.load(v);const e=month(s);expect(e.autonomy.firms[0].capitalInUse.quantity).toBe(0);expect(e.autonomy.firms[0].pendingCapacity).toBe(3);expect(e.autonomy.firms[0].idleReason).toBe('equipment');});
test('production resumes when its real labor constraint is removed',()=>{const {s}=create(),v=s.snapshot();v.systems.economy.rules.laborParticipationBps=0;s.load(v);month(s);const restored=s.snapshot();restored.systems.economy.rules.laborParticipationBps=5000;s.load(restored);expect(own(month(s)).workers).toBeGreaterThan(0);});
test('cargo, reserves, household inventories and history survive deterministic continuation',()=>{const a=create({trade:true}),b=create({trade:true});month(a.s);b.s.load(a.s.snapshot());for(let i=0;i<4;i++){month(a.s);month(b.s);}expect(b.s.serialize()).toBe(a.s.serialize());});
test('v3 save migration creates no cash, goods or invented past household production',()=>{const {s}=create({trade:true}),v=s.snapshot(),cash=s.economicReport().cash;delete v.systems.economy.householdEconomy;delete v.systems.economy.agriculture;delete v.systems.economy.trade.routing;s.load(v);expect(s.economicReport().cash).toBe(cash);expect(s.economySummary().householdEconomy.rows.every(r=>r.inventories.every(s=>!s.quantity))).toBe(true);expect(s.economySummary().trade.routing.cargo).toEqual([]);expect(s.economyAnalytics().monthly).toEqual([]);});
for(const size of [1,2])test(`household stocks and in-transit cash match direct simulation with ${size} workers`,async()=>{const a=create({trade:true}),b=create({trade:true}),pool=new EconomyPool({size,createWorker:()=>new Worker(path.resolve('scripts/economy-worker.cjs'))});try{for(let i=0;i<4;i++){month(a.s);await b.s.stepAsync(days(b.s),pool);expect(b.s.serialize()).toBe(a.s.serialize());}}finally{pool.dispose();}});
test('invalid cargo escrow fails loading atomically',()=>{const {s}=create({trade:true});month(s);const before=s.serialize(),v=s.snapshot();v.systems.economy.trade.routing.cargo[0].escrowMinor++;expect(()=>s.load(v)).toThrow();expect(s.serialize()).toBe(before);});
test('retained realized profit can be paid later without distributing startup capital',()=>{const {s}=create({trade:true}),v=s.snapshot();v.systems.economy.autonomy.rules.profitPayoutBps=0;s.load(v);const first=month(s),cash=s.economicReport().cash;expect(first.householdEconomy.profitClaims[0].closing).toBeGreaterThan(0);const next=s.snapshot();next.systems.economy.autonomy.rules.profitPayoutBps=10000;s.load(next);const e=month(s),f=e.enterprises[0];expect(f.stats.payout).toBeGreaterThan(f.stats.profit);expect(e.householdEconomy.profitClaims[0].closing).toBe(0);expect(s.economicReport().cash).toBe(cash);});
test('equipment moves through two markets and cannot be installed before arrival',()=>{const {s}=create({trade:true}),v=s.snapshot(),e=v.systems.economy,seller=e.enterprises[0];seller.recipeId='forge-tools';stock(seller,'tools').quantity=100;const buyer={...structuredClone(seller),id:'equipment-buyer',provinceId:'province:00003',ownerRef:{kind:'household',id:'household-far'},recipeId:'grow-grain',cashMinor:1000,inventories:e.goods.map(g=>({goodId:g.id,quantity:0,bookValueMinor:0}))};e.enterprises.push(buyer);const c=require('../shared/autonomous-economy.cjs').record(buyer);c.status='pending';c.pendingCapacity=2;e.autonomy.firms.push(c);e.householdEconomy.profitClaims.push({enterpriseId:buyer.id,opening:0,earned:0,distributed:0,closing:0});v.systems.settlements.placements.push({enterpriseId:buyer.id,settlementId:v.systems.settlements.rows.find(r=>r.provinceId===buyer.provinceId).id,kind:'settlement'});for(const m of e.markets)m.goods.find(g=>g.goodId==='tools').priceMinor=m.provinceIds.includes(buyer.provinceId)?30:3;s.load(v);month(s);expect(s.enterpriseSummary(buyer.id).capacityBatches).toBe(0);month(s);expect(stock(s.enterpriseSummary(buyer.id),'tools').quantity).toBe(2);expect(s.enterpriseSummary(buyer.id).capacityBatches).toBe(0);month(s);expect(s.enterpriseSummary(buyer.id).capacityBatches).toBe(2);expect(stock(s.enterpriseSummary(buyer.id),'tools').quantity).toBe(0);});
test('installed capital still wears out and generates a physical replacement request',()=>{const {s}=create({trade:true}),v=s.snapshot(),e=v.systems.economy,c=e.autonomy.firms[0];e.autonomy.rules.capitalLifetimeMonths=2;c.baseCapacity=0;c.capitalInUse={quantity:2,bookValueMinor:20,remainder:0};e.enterprises[0].capacityBatches=2;const b=e.autonomy.goods.find(g=>g.goodId==='tools');b.capitalOpening=2;b.capitalClosing=2;s.load(v);const next=month(s);expect(next.autonomy.firms[0].capitalInUse.quantity).toBe(1);expect(next.autonomy.firms[0].replacementCapacity).toBe(1);expect(next.autonomy.goods.find(g=>g.goodId==='tools').capitalRetired).toBe(1);});
