const names={food:'Продовольствие',grain:'Зерно',flour:'Мука',tools:'Инструменты',iron:'Железо','iron-ore':'Руда',timber:'Древесина',charcoal:'Уголь',fiber:'Волокно',yarn:'Пряжа',cloth:'Ткань',clothing:'Одежда'};
const format=new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1});
const node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
export class EconomyPanel{
  constructor(map,simulation,inspector){
    this.map=map;this.simulation=simulation;this.inspector=inspector;this.scope='world';this.offset=0;this.metric='foodBps';this.monthly=[];this.annual=[];this.generation=0;this.dev=new URLSearchParams(location.search).get('economyDev')==='1';
    this.panel=inspector.panel('economy','live-economy');const tab=node('button','Экономика');tab.dataset.tab='economy';tab.onclick=()=>this.open();inspector.nav.prepend(tab);this.toggle=node('button','Экономика');this.toggle.id='economy-toggle';this.toggle.onclick=()=>inspector.active==='economy'&&!inspector.root.hidden?inspector.hide():this.open();document.querySelector('.game-controls').append(this.toggle);
    this.unsubscribe=simulation.subscribe(event=>{if(['gameLoaded'].includes(event.type)){this.monthly=[];this.annual=[];this.generation++;}if(['economyUpdated','gameLoaded','viewUpdated'].includes(event.type)||event.type==='stateChanged'&&!['time','clock'].includes(event.kind))this.schedule();});
    map.canvas.addEventListener('regionselect',()=>{if(inspector.active==='economy'&&!inspector.root.hidden){this.generation++;if(this.scope!=='world')this.scope='province';inspector.show('economy');this.schedule();}});
    const original=inspector.selectTab.bind(inspector);inspector.selectTab=kind=>kind==='economy'?this.open():original(kind);
  }
  open(){this.inspector.show('economy');this.refresh();}
  schedule(){if(this.inspector.root.hidden||this.inspector.active!=='economy'||this.timer)return;this.timer=setTimeout(()=>{this.timer=null;this.refresh();},250);}
  async refresh(){
    if(this.busy){this.schedule();return;}if(this.inspector.root.hidden||this.inspector.active!=='economy')return;this.busy=true;const generation=this.generation,provinceId=this.inspector.provinceId||this.map.selectedId,id=this.scope==='country'?this.simulation.ownership.get(provinceId):this.scope==='province'?provinceId:undefined;
    try{const last=this.monthly.at(-1),result=await this.simulation.economyAnalytics({scope:this.scope,id,detail:this.dev,offset:this.offset,after:this.scope==='world'&&last?last.year*12+last.month:0});if(generation!==this.generation){this.schedule();return;}if(this.scope==='world'){const points=new Map(this.monthly.map(p=>[p.year*12+p.month,p]));for(const p of result.monthly)points.set(p.year*12+p.month,p);this.monthly=[...points.values()].sort((a,b)=>a.year*12+a.month-b.year*12-b.month).slice(-120);const years=new Map(this.annual.map(p=>[p.year,p]));for(const p of result.annual)years.set(p.year,p);this.annual=[...years.values()].sort((a,b)=>a.year-b.year).slice(-200);}if(!this.inspector.root.hidden&&this.inspector.active==='economy')this.render(result);}catch(error){this.panel.replaceChildren(node('p',`Не удалось получить показатели: ${error.message}`));}finally{this.busy=false;}
  }
  render(data){
    this.panel.replaceChildren();const header=node('header'),title=node('h2','Экономика'),close=node('button','Закрыть');close.onclick=()=>this.inspector.hide();header.append(title,close);this.panel.append(header);const scopes=node('nav');for(const [scope,label]of [['world','Мир'],['country','Страна'],['province','Регион']]){const b=node('button',label);b.setAttribute('aria-pressed',String(this.scope===scope));b.disabled=scope!=='world'&&!this.inspector.provinceId&&!this.map.selectedId;b.onclick=()=>{this.scope=scope;this.offset=0;this.generation++;this.refresh();};scopes.append(b);}this.panel.append(scopes);
    if(!data.available){this.panel.append(node('p',data.reason));return;}if(!data.completed){this.panel.append(node('p','Первый экономический месяц ещё не завершён.'));return;}const p=data.point,previous=this.scope==='world'?this.monthly.at(-2):null;
    if(this.scope==='country')this.panel.append(node('h3',this.simulation.countries.get(data.id)?.name||'Выбранная страна'),node('p','Учитываются провинции, принадлежащие выбранной стране сейчас. Выберите страну через её провинцию на карте.'));
    if(!data.autonomous)this.panel.append(node('p','Сценарная экономика: автономное развитие отключено.'));
    this.panel.append(node('small',`Данные за завершённый месяц ${p.year}-${String(p.month).padStart(2,'0')}.`));
    const cards=node('div');cards.className='economy-metrics';for(const [key,label,unit,tip]of [['foodBps','Продовольствие','%','Доля физически удовлетворённой месячной потребности'],['active','Работают','',`Из ${format.format(p.enterprises)} моделируемых предприятий`],['workers','Занятость','','Работники моделируемых предприятий; это не показатель безработицы'],['batches','Производство','','Произведённые партии за завершённый месяц']]){const card=node('div'),value=node('strong',key==='foodBps'?(p.foodNeed?`${Math.round(p[key]/100)}%`:'\u2014'):format.format(p[key]));card.title=tip;card.append(node('span',label),value);if(previous){const delta=p[key]-previous[key];card.append(node('small',`${delta>0?'+':''}${key==='foodBps'?(delta/100).toFixed(1)+' п.п.':format.format(delta)} за месяц`));}cards.append(card);}this.panel.append(cards);
    const select=node('select');select.setAttribute('aria-label','Показатель графика');for(const [value,label]of [['foodBps','Продовольствие'],['batches','Производство'],['population','Население'],['active','Предприятия']])select.add(new Option(label,value));select.value=this.metric;select.onchange=()=>{this.metric=select.value;this.render(data);};this.panel.append(select);
    const range=node('select');range.setAttribute('aria-label','Период графика');range.add(new Option('Месяцы · до 10 лет','monthly'));range.add(new Option('Годы · до 200 лет','annual'));range.value=this.range||'monthly';range.onchange=()=>{this.range=range.value;this.render(data);};this.panel.append(range);
    const points=this.scope==='world'?(this.range==='annual'?this.annual:this.monthly):[];if(points.length>1){this.panel.append(this.chart(points));this.panel.append(node('small',`${points[0].year}.${String(points[0].month).padStart(2,'0')} — ${points.at(-1).year}.${String(points.at(-1).month).padStart(2,'0')}`));}else this.panel.append(node('p',this.scope==='world'?'История появится после завершённых месяцев.':'История этого уровня не записывалась; показаны текущие данные.'));
    this.panel.append(node('p',this.metric==='foodBps'?'Обеспеченность учитывает реально потреблённое продовольствие, включая оплаченные поставки предыдущего месяца.':this.metric==='batches'?'Месячный выпуск в партиях разных рецептов; это не ВВП.':this.metric==='active'?'Предприятия, которые произвели товар за месяц.':'Численность населения на конец периода.'));
    this.panel.append(node('h3','Требует внимания'));if(!data.attention.length)this.panel.append(node('p','Существенных проблем обеспечения в этих данных не выявлено.'));for(const warning of data.attention){const b=node('button',warning.text);b.className='economy-warning';b.onclick=()=>{if(warning.provinceId){this.inspector.provinceId=warning.provinceId;this.map.selectedId=warning.provinceId;this.map.invalidate();this.scope='province';this.offset=0;this.generation++;this.refresh();}};this.panel.append(b);}
    if(data.market){this.panel.append(node('h3',`Местный рынок · ${data.market.id}`));const table=node('table');for(const g of data.market.prices.filter(g=>['food','grain','flour','tools'].includes(g.goodId))){const row=node('tr');row.append(node('td',names[g.goodId]||g.goodId),node('td',format.format(g.price)));table.append(row);}this.panel.append(table,node('p',`Поставки всего рынка: импорт ${format.format(data.market.imports.reduce((n,f)=>n+f.quantity,0))}, экспорт ${format.format(data.market.exports.reduce((n,f)=>n+f.quantity,0))}.`));}
    if(this.dev){const details=node('details');details.append(node('summary',`DEV · диагностика · ${data.diagnostics.enterpriseCount} предприятий`),node('pre',JSON.stringify(data.diagnostics,null,2)));for(const [delta,label]of [[-20,'Предыдущие'],[20,'Следующие']]){const button=node('button',label);button.disabled=delta<0?this.offset===0:this.offset+20>=data.diagnostics.enterpriseCount;button.onclick=()=>{this.offset=Math.max(0,this.offset+delta);this.generation++;this.refresh();};details.append(button);}this.panel.append(details);}
  }
  chart(points){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 360 130');svg.setAttribute('role','img');svg.setAttribute('aria-label','История выбранного показателя');const values=points.map(p=>this.range==='annual'&&this.metric==='batches'?p.totalBatches:this.range==='annual'&&this.metric==='foodBps'?(p.totalFoodNeed?Math.floor(p.totalFoodConsumed*10000/p.totalFoodNeed):0):p[this.metric]),min=this.metric==='foodBps'?0:Math.min(...values),max=this.metric==='foodBps'?10000:Math.max(...values,min+1),path=document.createElementNS(ns,'path');path.setAttribute('d',values.map((v,i)=>`${i?'L':'M'}${10+i*340/(values.length-1)},${110-(v-min)*90/(max-min)}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#c8b88a');path.setAttribute('stroke-width','2');svg.append(path);for(const [value,y]of [[max,15],[min,125]]){const t=document.createElementNS(ns,'text');t.setAttribute('x','10');t.setAttribute('y',String(y));t.setAttribute('fill','#bcc8c5');t.setAttribute('font-size','10');t.textContent=this.metric==='foodBps'?`${value/100}%`:format.format(value);svg.append(t);}return svg;}
}
