// Optional deterministic enterprise controller. No generation, RNG or cash injection.
const {number,compare}=require('./settlements.cjs');
const safe=n=>Number.isSafeInteger(n)&&n>=0;
const add=(a,b)=>number(BigInt(a)+BigInt(b)),mul=(a,b)=>number(BigInt(a)*BigInt(b));
const defaults={windowMonths:6,profitPayoutBps:10000,reserveMonths:4,inputReserveMonths:2,outputReserveMonths:1,closeMonths:24,cooldownMonths:12,growthBps:1000,entryMonths:12,entryCapacity:10,organizationCostPerBatch:16,investorReserveMonths:24,capitalGoodId:'tools',capitalPerBatch:1,capitalLifetimeMonths:120,durableLifetimeMonths:60,birthRateBps:300,deathRateBps:250,urbanizationBps:5,urbanJobsPerMigrant:1};
function fields(o,keys){if(!o||Object.getPrototypeOf(o)!==Object.prototype||Object.keys(o).length!==keys.length||keys.some(k=>!Object.hasOwn(o,k)))throw Error('Autonomy: invalid fields');}
const record=e=>({enterpriseId:e.id,status:'active',plannedBatches:e.capacityBatches,baseCapacity:e.capacityBatches,salesAverage:0,salesRemainder:0,observations:0,badMonths:0,goodMonths:0,cooldown:0,pendingCapacity:0,replacementCapacity:0,capitalInUse:{quantity:0,bookValueMinor:0,remainder:0},profitTotal:0,cashFlow:0,investment:0,depreciation:0,sold:0,idleReason:'demand'});
// Optional extension: old autonomy v1 saves retain their original demography.
function foodSecurity(e,enabled=true){return {version:1,enabled,windowMonths:12,graceMonths:6,maxBirthReductionBps:5000,maxExtraDeathRateBps:250,households:e.households.map(h=>({householdId:h.id,deficitAverageBps:0,remainder:0,deficitMonths:0}))};}
function configureFoodFeedback(state,enabled){const next=structuredClone(state),e=next.systems.economy;if(!e?.autonomy)throw Error('Autonomy: food feedback requires autonomy');if(!e.autonomy.foodSecurity)e.autonomy.foodSecurity=foodSecurity(e,enabled);else e.autonomy.foodSecurity.enabled=enabled;validate(e);return next;}
function foodEffects(e){
  const f=e.autonomy?.foodSecurity,result=new Map();if(!f?.enabled)return result;
  const households=new Map(e.households.map(h=>[h.id,h]));
  for(const h of f.households){if(h.deficitMonths<f.graceMonths)continue;const exposure=Math.min(f.windowMonths,h.deficitMonths-f.graceMonths+1),severity=number(BigInt(h.deficitAverageBps)*BigInt(exposure)/BigInt(f.windowMonths));result.set(households.get(h.householdId).provinceId,{birthReductionBps:number(BigInt(severity)*BigInt(f.maxBirthReductionBps)/10000n),extraDeathRateBps:number(BigInt(severity)*BigInt(f.maxExtraDeathRateBps)/10000n)});}
  return result;
}
function updateFoodHistory(e){
  const f=e.autonomy.foodSecurity;if(!f)return;const houses=new Map(e.households.map(h=>[h.id,h])),ids=new Set(e.rules.consumerNeeds.filter(n=>n.goodId===e.rules.foodGoodId&&n.usage==='consumable').map(n=>n.id));
  for(const h of f.households){let need=0,purchased=0;for(const n of houses.get(h.householdId).consumerState)if(ids.has(n.needId)){need=add(need,n.stats.need);purchased=add(purchased,n.stats.purchased);}const deficit=need?number(BigInt(need-purchased)*10000n/BigInt(need)):0,numerator=BigInt(h.deficitAverageBps)*BigInt(f.windowMonths-1)+BigInt(deficit)+BigInt(h.remainder);h.deficitAverageBps=number(numerator/BigInt(f.windowMonths));h.remainder=Number(numerator%BigInt(f.windowMonths));h.deficitMonths=deficit>=1000?add(h.deficitMonths,1):Math.max(0,h.deficitMonths-1);}
}
function enable(state,overrides={}){
  if(!state.systems.economy||!state.systems.settlements)throw Error('Autonomy: procedural economy and settlements required');
  if(state.systems.economy.autonomy)throw Error('Autonomy: already enabled');
  const next=structuredClone(state),e=next.systems.economy;
  const {foodFeedback=true,...rules}=overrides;
  e.autonomy={version:1,rules:{...defaults,...rules},firms:e.enterprises.map(record),wear:e.households.map(h=>({householdId:h.id,remainders:h.inUse.map(s=>({goodId:s.goodId,remainder:0}))})),events:{opened:0,closed:0,reactivated:0,expanded:0,contracted:0,investment:0,maintenance:0},goods:e.goods.map(g=>({goodId:g.id,inUseRetired:0,capitalOpening:0,capitalAdded:0,capitalRetired:0,capitalClosing:0})),shortages:e.markets.flatMap(m=>m.goods.map(g=>({marketId:m.id,goodId:g.goodId,months:0}))),urbanized:0};
  e.autonomy.foodSecurity=foodSecurity(e,foodFeedback);
  validate(e);
  // Explicit activation changes future rates, never current counts or residuals.
  for(const c of next.systems.population.cohorts){c.birthRateBps=e.autonomy.rules.birthRateBps;c.deathRateBps=e.autonomy.rules.deathRateBps;}
  return next;
}
function validate(e){
  const a=e.autonomy;if(!Object.hasOwn(e,'autonomy'))return;
  fields(a,['version','rules','firms','wear','events','goods','shortages','urbanized',...(a&&Object.hasOwn(a,'foodSecurity')?['foodSecurity']:[])]);fields(a.rules,Object.keys(defaults));
  const r=a.rules;
  if(a.version!==1||!e.rules.consumerNeeds||Object.entries(r).some(([k,v])=>k==='capitalGoodId'?!e.goods.some(g=>g.id===v):!safe(v))||['windowMonths','reserveMonths','inputReserveMonths','closeMonths','cooldownMonths','entryMonths','capitalPerBatch','capitalLifetimeMonths','durableLifetimeMonths','urbanJobsPerMigrant'].some(k=>!r[k])||r.windowMonths>120||r.profitPayoutBps>10000||r.growthBps>10000||r.urbanizationBps>10000||r.birthRateBps>10000||r.deathRateBps>10000)throw Error('Autonomy: invalid rules');
  fields(a.events,['opened','closed','reactivated','expanded','contracted','investment','maintenance']);if(!safe(a.urbanized)||Object.values(a.events).some(v=>!safe(v)))throw Error('Autonomy: invalid events');
  const ids=new Set(e.enterprises.map(f=>f.id)),seen=new Set();
  for(const f of a.firms){fields(f,Object.keys(record({id:'',capacityBatches:0})));fields(f.capitalInUse,['quantity','bookValueMinor','remainder']);if(!ids.has(f.enterpriseId)||seen.has(f.enterpriseId)||!['active','dormant','pending'].includes(f.status)||!['demand','materials','money','labor','closed','none'].includes(f.idleReason)||Object.entries(f).some(([k,v])=>!['enterpriseId','status','idleReason','capitalInUse','profitTotal','cashFlow'].includes(k)&&!safe(v))||!Number.isSafeInteger(f.profitTotal)||!Number.isSafeInteger(f.cashFlow)||Object.values(f.capitalInUse).some(v=>!safe(v))||f.capitalInUse.remainder>=r.capitalLifetimeMonths||f.salesRemainder>=r.windowMonths||!f.capitalInUse.quantity&&f.capitalInUse.bookValueMinor)throw Error('Autonomy: invalid enterprise controller');seen.add(f.enterpriseId);}
  if(seen.size!==ids.size)throw Error('Autonomy: missing enterprise controller');
  const households=new Map(e.households.map(h=>[h.id,h]));seen.clear();
  for(const w of a.wear){fields(w,['householdId','remainders']);const h=households.get(w.householdId);if(!h||seen.has(w.householdId)||w.remainders.length!==h.inUse.length)throw Error('Autonomy: invalid wear');seen.add(w.householdId);const goods=new Set();for(const s of w.remainders){fields(s,['goodId','remainder']);if(goods.has(s.goodId)||!h.inUse.some(i=>i.goodId===s.goodId)||!safe(s.remainder)||s.remainder>=r.durableLifetimeMonths)throw Error('Autonomy: invalid wear remainder');goods.add(s.goodId);}}
  if(seen.size!==households.size)throw Error('Autonomy: missing wear');
  if(Object.hasOwn(a,'foodSecurity')){const f=a.foodSecurity;fields(f,['version','enabled','windowMonths','graceMonths','maxBirthReductionBps','maxExtraDeathRateBps','households']);if(f.version!==1||typeof f.enabled!=='boolean'||!safe(f.windowMonths)||!f.windowMonths||f.windowMonths>120||!safe(f.graceMonths)||!f.graceMonths||f.graceMonths>120||!safe(f.maxBirthReductionBps)||f.maxBirthReductionBps>10000||!safe(f.maxExtraDeathRateBps)||f.maxExtraDeathRateBps>1000||!Array.isArray(f.households))throw Error('Autonomy: invalid food security');seen.clear();for(const h of f.households){fields(h,['householdId','deficitAverageBps','remainder','deficitMonths']);if(!households.has(h.householdId)||seen.has(h.householdId)||!safe(h.deficitAverageBps)||h.deficitAverageBps>10000||!safe(h.remainder)||h.remainder>=f.windowMonths||!safe(h.deficitMonths))throw Error('Autonomy: invalid food history');seen.add(h.householdId);}if(seen.size!==households.size)throw Error('Autonomy: missing food history');}
  seen.clear();for(const b of a.goods){fields(b,['goodId','inUseRetired','capitalOpening','capitalAdded','capitalRetired','capitalClosing']);if(!e.goods.some(g=>g.id===b.goodId)||seen.has(b.goodId)||Object.entries(b).some(([k,v])=>k!=='goodId'&&!safe(v))||BigInt(b.capitalOpening)+BigInt(b.capitalAdded)-BigInt(b.capitalRetired)!==BigInt(b.capitalClosing))throw Error('Autonomy: invalid capital balance');seen.add(b.goodId);}
  if(seen.size!==e.goods.length)throw Error('Autonomy: missing balances');
  if(e.stats.monthsProcessed){const installed=a.firms.reduce((n,f)=>add(n,f.capitalInUse.quantity),0);if(installed!==a.goods.find(g=>g.goodId===r.capitalGoodId).capitalClosing||a.goods.some(g=>g.goodId!==r.capitalGoodId&&(g.capitalOpening||g.capitalAdded||g.capitalRetired||g.capitalClosing)))throw Error('Autonomy: inconsistent installed capital');}
  const markets=new Set(e.markets.map(m=>m.id));seen.clear();for(const s of a.shortages){fields(s,['marketId','goodId','months']);const key=s.marketId+':'+s.goodId;if(!markets.has(s.marketId)||!e.goods.some(g=>g.id===s.goodId)||seen.has(key)||!safe(s.months))throw Error('Autonomy: invalid shortage history');seen.add(key);}if(seen.size!==e.markets.length*e.goods.length)throw Error('Autonomy: missing shortage history');
}
function signedAdd(a,b){const v=BigInt(a)+BigInt(b);if(v>BigInt(Number.MAX_SAFE_INTEGER)||v<BigInt(Number.MIN_SAFE_INTEGER))throw Error('Autonomy: integer overflow');return Number(v);}
function retire(stock,quantity,take){const value=quantity?take(stock,quantity):0;return value;}
function workingReserve(e,enterprise,recipe,market,controller,includeCapital=true){
  const r=e.autonomy.rules,batches=Math.min(enterprise.capacityBatches,Math.max(controller.plannedBatches,Math.ceil(controller.salesAverage/recipe.output.quantity))),horizon=mul(batches,r.reserveMonths);
  let reserve=mul(mul(horizon,recipe.workersPerBatch),enterprise.wagePerWorkerMinor);
  for(const input of recipe.inputs){const held=enterprise.inventories.find(s=>s.goodId===input.goodId).quantity;reserve=add(reserve,mul(Math.max(0,mul(horizon,input.quantity)-held),market.goods.find(g=>g.goodId===input.goodId).priceMinor));}
  // Earmark only an actual pending installation, not hypothetical full capacity.
  if(includeCapital&&controller.pendingCapacity){const held=enterprise.inventories.find(s=>s.goodId===r.capitalGoodId).quantity;reserve=add(reserve,add(mul(controller.pendingCapacity,r.organizationCostPerBatch),mul(Math.max(0,mul(controller.pendingCapacity,r.capitalPerBatch)-held),market.goods.find(g=>g.goodId===r.capitalGoodId).priceMinor)));}
  return reserve;
}
function materialCost(enterprise,recipe,market){return recipe.inputs.reduce((n,i)=>{const stock=enterprise.inventories.find(s=>s.goodId===i.goodId),price=stock.quantity?number((BigInt(stock.bookValueMinor)+BigInt(stock.quantity)-1n)/BigInt(stock.quantity)):market.goods.find(g=>g.goodId===i.goodId).priceMinor;return add(n,mul(i.quantity,price));},0);}
function begin(e,old,population,marketAt,balance,take){
  const a=e.autonomy;if(!a)return null;const r=a.rules;
  for(const k of Object.keys(a.events))a.events[k]=0;
  const physical=new Map(a.goods.map(b=>{Object.assign(b,{inUseRetired:0,capitalOpening:0,capitalAdded:0,capitalRetired:0,capitalClosing:0});return [b.goodId,b];}));
  const houses=new Map(e.households.map(h=>[h.id,h]));
  const importedAt=new Map((e.trade?.householdStocks||[]).map(s=>[s.householdId,s]));
  for(const w of a.wear)for(const rem of w.remainders){const s=houses.get(w.householdId).inUse.find(s=>s.goodId===rem.goodId),n=BigInt(s.quantity)+BigInt(rem.remainder),q=Math.min(s.quantity,number(n/BigInt(r.durableLifetimeMonths)));rem.remainder=Number(n%BigInt(r.durableLifetimeMonths));retire(s,q,take);physical.get(s.goodId).inUseRetired=add(physical.get(s.goodId).inUseRetired,q);}
  const firms=new Map(a.firms.map(f=>[f.enterpriseId,f])),recipes=new Map(e.recipes.map(v=>[v.id,v]));
  const capacities=new Map(),people=new Map();for(const c of population.cohorts)people.set(c.territoryId,add(people.get(c.territoryId)||0,c.count));
  for(const enterprise of e.enterprises){const f=firms.get(enterprise.id),recipe=recipes.get(enterprise.recipeId),key=marketAt.get(enterprise.provinceId).id+':'+recipe.output.goodId;capacities.set(key,add(capacities.get(key)||0,mul(enterprise.capacityBatches,recipe.output.quantity)));}
  // Bounded nominal wage adaptation follows observed losses or sustained sales.
  // No price floor: a producer can still lose money and retain unused capacity.
  for(const enterprise of e.enterprises){const f=firms.get(enterprise.id),recipe=recipes.get(enterprise.recipeId),market=marketAt.get(enterprise.provinceId);if(f.observations<r.windowMonths)continue;const inputs=materialCost(enterprise,recipe,market),gross=mul(recipe.output.quantity,market.goods.find(g=>g.goodId===recipe.output.goodId).priceMinor),target=Math.max(1,Math.min(64,number(BigInt(Math.max(0,gross-inputs))*8000n/10000n/BigInt(recipe.workersPerBatch))));if(enterprise.stats.profit<0||f.goodMonths>=r.windowMonths)enterprise.wagePerWorkerMinor=Math.max(1,enterprise.wagePerWorkerMinor+Math.sign(target-enterprise.wagePerWorkerMinor));}
  // Physical needs, current purchasing power and contingent future wages are
  // distinct signals. Past wages/dividends already belong to opening cash.
  const forecast=new Map(),physicalNeed=new Map(),expectedWages=new Map(),byOutput=new Map(),byRecipe=new Map();for(const recipe of e.recipes){if(!byOutput.has(recipe.output.goodId))byOutput.set(recipe.output.goodId,[]);byOutput.get(recipe.output.goodId).push(recipe);}
  const householdNeeds=new Map();
  for(const h of e.households){let imported=importedAt.get(h.id)?.quantity||0;const targets=new Map(),rows=[];for(const n of e.rules.consumerNeeds){const rem=n.usage==='consumable'?h.consumerState.find(s=>s.needId===n.id).remainder:0,target=number((BigInt(people.get(h.provinceId)||0)*BigInt(n.perPersonNumerator)+BigInt(rem))/BigInt(n.perPersonDenominator)),held=h.inUse.find(s=>s.goodId===n.goodId)?.quantity||0,need=n.usage==='durable'?Math.max(0,target-Math.max(held,targets.get(n.goodId)||0)):target;if(n.usage==='durable')targets.set(n.goodId,Math.max(targets.get(n.goodId)||0,target));const covered=n.goodId===e.rules.foodGoodId&&n.usage==='consumable'?Math.min(imported,need):0;imported-=covered;rows.push({goodId:n.goodId,need:need-covered});const key=marketAt.get(h.provinceId).id+':'+n.goodId;physicalNeed.set(key,add(physicalNeed.get(key)||0,need-covered));}householdNeeds.set(h.id,rows);}
  for(const enterprise of e.enterprises){const recipe=recipes.get(enterprise.recipeId),key=marketAt.get(enterprise.provinceId).id+':'+recipe.id;if(!byRecipe.has(key))byRecipe.set(key,[]);byRecipe.get(key).push(enterprise);}
  const outgoing=new Map(e.goods.map(g=>[g.id,new Set()])),indegree=new Map(e.goods.map(g=>[g.id,0]));for(const recipe of e.recipes)for(const input of recipe.inputs)if(!outgoing.get(recipe.output.goodId).has(input.goodId)){outgoing.get(recipe.output.goodId).add(input.goodId);indegree.set(input.goodId,indegree.get(input.goodId)+1);}
  const queue=[...indegree].filter(([,n])=>!n).map(([id])=>id).sort(compare),order=[];while(queue.length){const id=queue.shift();order.push(id);for(const input of outgoing.get(id)){indegree.set(input,indegree.get(input)-1);if(!indegree.get(input))queue.push(input);}}
  for(const m of e.markets)for(const goodId of order){const key=m.id+':'+goodId,total=capacities.get(key)||0;if(!total)continue;for(const recipe of byOutput.get(goodId)||[])for(const enterprise of byRecipe.get(m.id+':'+recipe.id)||[]){const batches=number((BigInt(physicalNeed.get(key)||0)*BigInt(enterprise.capacityBatches)+BigInt(total)-1n)/BigInt(total));for(const input of recipe.inputs){const k=m.id+':'+input.goodId;physicalNeed.set(k,add(physicalNeed.get(k)||0,mul(batches,input.quantity)));}}}
  const availableLabor=new Map([...people].map(([id,n])=>[id,number(BigInt(n)*BigInt(e.rules.laborParticipationBps)/10000n)]));
  for(const enterprise of e.enterprises){const f=firms.get(enterprise.id),recipe=recipes.get(enterprise.recipeId),m=marketAt.get(enterprise.provinceId);
    // A single affordable recovery batch can restart payroll. The estimate is
    // bounded by opening inputs, cash and shared local labor; it is never cash.
    const recovery=(physicalNeed.get(m.id+':'+recipe.output.goodId)||0)>0&&enterprise.inventories.find(s=>s.goodId===recipe.output.goodId).quantity<recipe.output.quantity?1:0;let batches=Math.min(enterprise.capacityBatches,Math.max(f.plannedBatches,Math.ceil(f.salesAverage/recipe.output.quantity),recovery),Math.floor((availableLabor.get(enterprise.provinceId)||0)/recipe.workersPerBatch));if(f.status==='dormant'&&f.cooldown>1)batches=0;const wage=mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor);if(wage)batches=Math.min(batches,Math.floor(enterprise.cashMinor/wage));for(const input of recipe.inputs)batches=Math.min(batches,Math.floor(enterprise.inventories.find(s=>s.goodId===input.goodId).quantity/input.quantity));availableLabor.set(enterprise.provinceId,(availableLabor.get(enterprise.provinceId)||0)-mul(batches,recipe.workersPerBatch));expectedWages.set(enterprise.provinceId,add(expectedWages.get(enterprise.provinceId)||0,mul(batches,wage)));}
  for(const h of e.households){let budget=add(h.cashMinor,expectedWages.get(h.provinceId)||0);const m=marketAt.get(h.provinceId);for(const row of householdNeeds.get(h.id)){const price=m.goods.find(g=>g.goodId===row.goodId).priceMinor,q=Math.min(row.need,Math.floor(budget/price));budget-=mul(q,price);const key=m.id+':'+row.goodId;forecast.set(key,add(forecast.get(key)||0,q));}}
  // Cyclic recipes retain observed demand; forecasts never recurse forever.
  for(const m of e.markets){
    for(const g of m.goods){const key=m.id+':'+g.goodId;if(!order.includes(g.goodId)||g.goodId===r.capitalGoodId)forecast.set(key,Math.max(forecast.get(key)||0,g.stats.inputDemand));}
    for(const goodId of order){
      const key=m.id+':'+goodId,demand=forecast.get(key)||0,total=capacities.get(key)||0;if(!total)continue;
      for(const recipe of byOutput.get(goodId)||[])for(const enterprise of byRecipe.get(m.id+':'+recipe.id)||[]){
        const f=firms.get(enterprise.id),share=number((BigInt(demand)*BigInt(enterprise.capacityBatches)*BigInt(recipe.output.quantity)+BigInt(total)-1n)/BigInt(total)),desired=Math.max(share,f.salesAverage),out=enterprise.inventories.find(s=>s.goodId===goodId),target=mul(desired,r.outputReserveMonths+1),wage=mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor),recovery=(physicalNeed.get(key)||0)>0&&out.quantity<recipe.output.quantity&&enterprise.cashMinor>=wage?1:0;
        const batches=f.status==='pending'||f.status==='dormant'&&f.cooldown>1?0:Math.min(enterprise.capacityBatches,Math.max(recovery,Math.ceil((target-out.quantity)/recipe.output.quantity)));
        let anticipated=wage?Math.min(batches,Math.floor(enterprise.cashMinor/wage)):batches;
        for(const input of recipe.inputs)anticipated=Math.min(anticipated,Math.floor(enterprise.inventories.find(s=>s.goodId===input.goodId).quantity/input.quantity));
        let budget=Math.max(0,enterprise.cashMinor-mul(anticipated,wage)-mul(batches,wage));
        for(const input of recipe.inputs){
          const k=m.id+':'+input.goodId,held=enterprise.inventories.find(s=>s.goodId===input.goodId).quantity,price=m.goods.find(g=>g.goodId===input.goodId).priceMinor,target=mul(add(mul(batches,r.inputReserveMonths),anticipated),input.quantity),quantity=Math.min(Math.max(0,target-held),Math.floor(budget/price));budget-=mul(quantity,price);forecast.set(k,add(forecast.get(k)||0,quantity));
        }
      }
    }
  }
  for(const enterprise of e.enterprises){const f=firms.get(enterprise.id),recipe=recipes.get(enterprise.recipeId),m=marketAt.get(enterprise.provinceId),key=m.id+':'+recipe.output.goodId,total=capacities.get(key)||1,demand=forecast.get(key)||0,previousSold=f.sold,share=number((BigInt(demand)*BigInt(enterprise.capacityBatches)*BigInt(recipe.output.quantity)+BigInt(total)-1n)/BigInt(total)),out=enterprise.inventories.find(s=>s.goodId===recipe.output.goodId);
    const p=physical.get(r.capitalGoodId);p.capitalOpening=add(p.capitalOpening,f.capitalInUse.quantity);const n=BigInt(f.capitalInUse.quantity)+BigInt(f.capitalInUse.remainder),retired=Math.min(f.capitalInUse.quantity,number(n/BigInt(r.capitalLifetimeMonths)));f.capitalInUse.remainder=Number(n%BigInt(r.capitalLifetimeMonths));f.depreciation=retire(f.capitalInUse,retired,take);p.capitalRetired=add(p.capitalRetired,retired);const supported=add(f.baseCapacity,Math.floor(f.capitalInUse.quantity/r.capitalPerBatch));if(enterprise.capacityBatches>supported){const lost=enterprise.capacityBatches-supported;enterprise.capacityBatches=supported;f.pendingCapacity=add(f.pendingCapacity,lost);f.replacementCapacity=add(f.replacementCapacity,lost);a.events.contracted++;}
    f.investment=0;f.sold=0;f.cashFlow=-enterprise.cashMinor;f.cooldown=Math.max(0,f.cooldown-1);
    const recovery=(physicalNeed.get(key)||0)>0&&out.quantity<recipe.output.quantity&&enterprise.cashMinor>=mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor)?1:0,expectedPrice=Math.max(m.goods.find(g=>g.goodId===recipe.output.goodId).priceMinor,previousSold?number(BigInt(enterprise.stats.revenue)/BigInt(previousSold)):0),viable=BigInt(expectedPrice)*BigInt(recipe.output.quantity)>=BigInt(add(materialCost(enterprise,recipe,m),mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor)));
    if(f.status==='dormant'&&!f.cooldown&&viable&&(demand||recovery)&&out.quantity<add(mul(share,r.outputReserveMonths),recipe.output.quantity)&&enterprise.cashMinor>=mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor)){f.status='active';f.badMonths=0;a.events.reactivated++;}
    const desired=Math.max(share,f.salesAverage),target=mul(desired,r.outputReserveMonths+1),batches=Math.max(recovery,Math.ceil((target-out.quantity)/recipe.output.quantity));
    f.plannedBatches=f.status==='active'?Math.min(enterprise.capacityBatches,batches):0;if(!viable&&f.badMonths>=r.windowMonths)f.plannedBatches=Math.min(f.plannedBatches,Math.max(1,Math.ceil(f.plannedBatches/2)));f.idleReason=f.status==='dormant'?'closed':f.plannedBatches?'none':(physicalNeed.get(key)||0)>0&&enterprise.cashMinor<mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor)?'money':'demand';
  }
  return {firms,physical,forecast,physicalNeed,expectedWages};
}
function investmentOrders(e,context,marketAt,stocks,orders){
  const a=e.autonomy,r=a.rules,reserved=new Map();for(const o of orders)if(o.kind){const price=marketAt.get(o.buyer.provinceId).goods.find(g=>g.goodId===o.goodId).priceMinor;reserved.set(o.buyer.id,add(reserved.get(o.buyer.id)||0,mul(o.quantity,price)));}
  for(const enterprise of e.enterprises){
    const f=context.firms.get(enterprise.id);if(f.status==='dormant'||!f.pendingCapacity)continue;
    const recipe=e.recipes.find(v=>v.id===enterprise.recipeId),m=marketAt.get(enterprise.provinceId),capital=stocks.get(enterprise.id).get(r.capitalGoodId),desired=mul(f.pendingCapacity,r.capitalPerBatch),price=m.goods.find(g=>g.goodId===r.capitalGoodId).priceMinor,inputCommitment=reserved.get(enterprise.id)||0,batches=Math.min(enterprise.capacityBatches,Math.max(f.plannedBatches,Math.ceil(f.salesAverage/recipe.output.quantity))),payroll=mul(mul(mul(batches,recipe.workersPerBatch),enterprise.wagePerWorkerMinor),r.reserveMonths);
    // Purchased inputs replace part of the material cash reserve. Do not reserve
    // both the same order and its entire future material cost a second time.
    const reserve=Math.max(payroll,workingReserve(e,enterprise,recipe,m,f,false)-inputCommitment),organization=mul(f.pendingCapacity,r.organizationCostPerBatch),budget=Math.max(0,enterprise.cashMinor-reserve-inputCommitment-organization),quantity=Math.min(Math.max(0,desired-capital.quantity),Math.floor(budget/price));
    if(quantity){const g=m.goods.find(g=>g.goodId===r.capitalGoodId);g.stats.inputDemand=add(g.stats.inputDemand,quantity);orders.push({marketId:m.id,goodId:r.capitalGoodId,kind:2,buyer:enterprise,quantity});}
  }
}
function finish(e,context,marketAt,stocks,labor,houseAt,take,transfer,balance){
  const a=e.autonomy,r=a.rules;
  for(const enterprise of e.enterprises){const f=context.firms.get(enterprise.id),recipe=e.recipes.find(v=>v.id===enterprise.recipeId),m=marketAt.get(enterprise.provinceId),g=m.goods.find(v=>v.goodId===recipe.output.goodId),s=enterprise.stats;
    const numerator=BigInt(f.salesAverage)*BigInt(r.windowMonths-1)+BigInt(f.sold)+BigInt(f.salesRemainder);f.salesAverage=number(numerator/BigInt(r.windowMonths));f.salesRemainder=Number(numerator%BigInt(r.windowMonths));f.observations=add(f.observations,1);f.profitTotal=signedAdd(f.profitTotal,signedAdd(s.profit,-f.depreciation));
    const costs=add(mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor),materialCost(enterprise,recipe,m)),margin=BigInt(g.priceMinor)*BigInt(recipe.output.quantity)>BigInt(costs);
    const bad=(!f.sold&&!g.stats.affordableDemand&&!g.stats.inputDemand&&!(context.physicalNeed.get(m.id+':'+recipe.output.goodId)||0))||(!s.batches&&f.idleReason==='money'&&enterprise.cashMinor<mul(recipe.workersPerBatch,enterprise.wagePerWorkerMinor))||(s.revenue>0&&s.profit<0&&!margin&&f.observations>=r.windowMonths);f.badMonths=bad?add(f.badMonths,1):0;f.goodMonths=margin&&s.profit>0&&f.sold>=s.batches*recipe.output.quantity&&g.stats.shortage>0?add(f.goodMonths,1):0;
    if(f.status==='active'&&f.badMonths>=r.closeMonths){f.status='dormant';f.cooldown=r.cooldownMonths;a.events.closed++;}
    if(!f.cooldown&&!f.pendingCapacity&&f.goodMonths>=r.windowMonths){f.pendingCapacity=Math.max(1,number(BigInt(enterprise.capacityBatches)*BigInt(r.growthBps)/10000n));}
    if(f.pendingCapacity){const q=mul(f.pendingCapacity,r.capitalPerBatch),stock=stocks.get(enterprise.id).get(r.capitalGoodId),cost=mul(f.pendingCapacity,r.organizationCostPerBatch),workers=mul(f.pendingCapacity,recipe.workersPerBatch),reserve=workingReserve(e,enterprise,recipe,m,f,false);
      if(stock.quantity>=q&&enterprise.cashMinor>=add(cost,reserve)&&labor.get(enterprise.provinceId)>=workers){const value=take(stock,q);f.capitalInUse.quantity=add(f.capitalInUse.quantity,q);f.capitalInUse.bookValueMinor=add(f.capitalInUse.bookValueMinor,add(value,cost));context.physical.get(r.capitalGoodId).capitalAdded=add(context.physical.get(r.capitalGoodId).capitalAdded,q);transfer(enterprise,houseAt.get(enterprise.provinceId),cost);houseAt.get(enterprise.provinceId).stats.wages=add(houseAt.get(enterprise.provinceId).stats.wages,cost);labor.set(enterprise.provinceId,labor.get(enterprise.provinceId)-workers);enterprise.capacityBatches=add(enterprise.capacityBatches,f.pendingCapacity);f.investment=add(f.investment,add(value,cost));a.events.investment=add(a.events.investment,f.investment);if(f.replacementCapacity)a.events.maintenance=add(a.events.maintenance,number(BigInt(f.investment)*BigInt(Math.min(f.replacementCapacity,f.pendingCapacity))/BigInt(f.pendingCapacity)));if(f.pendingCapacity>f.replacementCapacity)a.events.expanded++;f.replacementCapacity=0;f.pendingCapacity=0;f.cooldown=r.cooldownMonths;f.status='active';}
    }
    // Existing capacity is legacy organizational capital; installed additions wear out.
    f.cashFlow=signedAdd(f.cashFlow,enterprise.cashMinor);const p=context.physical.get(r.capitalGoodId);p.capitalClosing=add(p.capitalClosing,f.capitalInUse.quantity);
  }
  for(const b of balance.values())b.closing=0;
  updateFoodHistory(e);
  const marketGoods=new Map(e.markets.flatMap(m=>m.goods.map(g=>[m.id+':'+g.goodId,g])));for(const s of a.shortages){const g=marketGoods.get(s.marketId+':'+s.goodId);s.months=g.stats.shortage>0?add(s.months,1):0;}
}
function develop(e,population,settlementState,hierarchy){
  const a=e.autonomy;if(!a)return settlementState;
  const r=a.rules,next=structuredClone(settlementState),profiles=require('./world-economy-rules.cjs').placement;
  const firms=new Map(e.enterprises.map(f=>[f.id,f])),controllers=new Map(a.firms.map(f=>[f.enterpriseId,f])),recipes=new Map(e.recipes.map(v=>[v.id,v])),people=new Map(),used=new Map(),jobs=new Map(),houseAt=new Map(e.households.map(h=>[h.provinceId,h]));
  for(const c of population.cohorts)people.set(c.territoryId,add(people.get(c.territoryId)||0,c.count));
  for(const f of e.enterprises)used.set(f.provinceId,add(used.get(f.provinceId)||0,f.stats.workers));
  for(const p of next.placements){const f=firms.get(p.enterpriseId);if(p.kind==='settlement'&&f.stats.revenue>0)jobs.set(f.provinceId,add(jobs.get(f.provinceId)||0,f.stats.workers));}
  // Entry is a funded pending workshop. Capital must be bought and installed before
  // its first batch. No stocks or equipment are initialized at entry.
  const rowsAt=new Map();for(const row of next.rows){if(!rowsAt.has(row.provinceId))rowsAt.set(row.provinceId,[]);rowsAt.get(row.provinceId).push(row);}
  const marketById=new Map(e.markets.map(m=>[m.id,m]));
  for(const shortage of a.shortages){
    if(shortage.months<r.entryMonths||e.stats.monthsProcessed%r.cooldownMonths)continue;
    const market=marketById.get(shortage.marketId),candidates=e.recipes.filter(v=>v.output.goodId===shortage.goodId);
    if(e.enterprises.some(f=>market.provinceIds.includes(f.provinceId)&&recipes.get(f.recipeId).output.goodId===shortage.goodId&&controllers.get(f.id).status==='pending'))continue;
    for(const recipe of candidates){const profile=profiles[recipe.id];if(!profile)continue;
      const capitalSupply=e.enterprises.some(f=>market.provinceIds.includes(f.provinceId)&&recipes.get(f.recipeId).output.goodId===r.capitalGoodId&&f.inventories.find(s=>s.goodId===r.capitalGoodId).quantity>=r.entryCapacity*r.capitalPerBatch);
      if(!capitalSupply)continue;
      const row=market.provinceIds.flatMap(id=>rowsAt.get(id)||[]).filter(s=>s.specializations.includes(profile.specialization)&&Math.floor((people.get(s.provinceId)||0)*e.rules.laborParticipationBps/10000)-(used.get(s.provinceId)||0)>=r.entryCapacity*recipe.workersPerBatch).sort((a,b)=>compare(a.id,b.id))[0];if(!row)continue;
      const h=houseAt.get(row.provinceId),prices=new Map(market.goods.map(g=>[g.goodId,g.priceMinor])),materials=recipe.inputs.reduce((n,i)=>add(n,mul(i.quantity,prices.get(i.goodId))),0),gross=mul(recipe.output.quantity,prices.get(recipe.output.goodId));if(gross<=add(materials,recipe.workersPerBatch))continue;const entryWage=Math.max(1,Math.min(8,number(BigInt(gross-materials)*8000n/10000n/BigInt(recipe.workersPerBatch)))),batchCost=add(materials,mul(recipe.workersPerBatch,entryWage)),funding=add(mul(r.entryCapacity,batchCost*r.reserveMonths+r.organizationCostPerBatch),mul(r.entryCapacity*r.capitalPerBatch,prices.get(r.capitalGoodId))),reserve=e.rules.consumerNeeds.filter(n=>n.priority==='essential').reduce((total,n)=>add(total,number((BigInt(people.get(row.provinceId)||0)*BigInt(n.perPersonNumerator)*BigInt(prices.get(n.goodId))*BigInt(r.investorReserveMonths)+BigInt(n.perPersonDenominator)-1n)/BigInt(n.perPersonDenominator))),0);
      if(h.cashMinor<add(funding,reserve))continue;
      const id=`auto-${e.stats.monthsProcessed}-${market.id.slice(7)}-${recipe.id}`;if(firms.has(id))continue;
      const enterprise={id,provinceId:row.provinceId,ownerRef:{kind:'household',id:h.id},recipeId:recipe.id,capacityBatches:0,wagePerWorkerMinor:entryWage,cashMinor:funding,inventories:e.goods.map(g=>({goodId:g.id,quantity:0,bookValueMinor:0})),stats:Object.fromEntries(['batches','workers','wages','inputsConsumedValue','productionCost','inputPurchases','revenue','cogs','profit','payout'].map(k=>[k,0]))};
      h.cashMinor-=funding;e.enterprises.push(enterprise);const controller=record(enterprise);controller.status='pending';controller.pendingCapacity=r.entryCapacity;a.firms.push(controller);firms.set(id,enterprise);controllers.set(id,controller);next.placements.push({enterpriseId:id,settlementId:row.id,kind:profile.external?'external':'settlement'});a.events.opened++;break;
    }
  }
  // Province-local rural -> urban transfer, capped by actual paid processor jobs
  // and food deliveries. Preserve demographic attributes and rate remainders.
  const urbanCounts=new Map();for(const c of population.cohorts)if(c.settlement==='urban')urbanCounts.set(c.territoryId,add(urbanCounts.get(c.territoryId)||0,c.count));
  const urbanByTuple=new Map();const tuple=c=>JSON.stringify([c.territoryId,c.cultureId,c.religionId,c.stratumId,c.literacyBps,c.birthRateBps,c.deathRateBps]);
  for(const c of population.cohorts)if(c.settlement==='urban')urbanByTuple.set(tuple(c),c);
  let movedTotal=0;
  for(const c of [...population.cohorts].sort((a,b)=>compare(a.id,b.id))){if(c.settlement!=='rural'||!c.count)continue;const h=houseAt.get(c.territoryId);if(!h)continue;
    const foodNeeds=h.consumerState.filter(s=>e.rules.consumerNeeds.find(n=>n.id===s.needId).priority==='essential');if(foodNeeds.some(s=>s.stats.purchased*100<s.stats.need*95))continue;
    const occupied=urbanCounts.get(c.territoryId)||0,slots=Math.max(0,(jobs.get(c.territoryId)||0)*r.urbanJobsPerMigrant-occupied),quantity=Math.min(slots,number(BigInt(c.count)*BigInt(r.urbanizationBps)/10000n));if(!quantity)continue;
    const key=tuple(c);let urban=urbanByTuple.get(key);if(!urban){urban={...c,id:`urban-${c.id}`,settlement:'urban',count:0,birthRemainder:0,deathRemainder:0};if(population.cohorts.some(v=>v.id===urban.id))throw Error('Autonomy: cohort ID collision');population.cohorts.push(urban);urbanByTuple.set(key,urban);}
    const previousUrbanCount=urban.count;urban.count=add(urban.count,quantity);
    for(const field of ['birthRemainder','deathRemainder']){const part=number(BigInt(c[field])*BigInt(quantity)/BigInt(c.count));c[field]-=part;urban[field]+=part;if(urban[field]>=120000){const units=Math.floor(urban[field]/120000);urban[field]%=120000;urban.count=field==='birthRemainder'?add(urban.count,units):number(BigInt(urban.count)-BigInt(units));population.stats[field==='birthRemainder'?'births':'deaths']=add(population.stats[field==='birthRemainder'?'births':'deaths'],units);}}
    c.count-=quantity;movedTotal=add(movedTotal,quantity);urbanCounts.set(c.territoryId,number(BigInt(urbanCounts.get(c.territoryId)||0)+BigInt(urban.count)-BigInt(previousUrbanCount)));
    if(!(rowsAt.get(c.territoryId)||[]).some(s=>s.classification==='urban')){const id=`settlement-${c.territoryId.slice(9)}-u01`;const row={id,provinceId:c.territoryId,type:'town',name:'Synthetic town '+c.territoryId.slice(9),classification:'urban',population:0,weight:1,position:null,capitalOf:[],specializations:['food-processing','textiles']};next.rows.push(row);rowsAt.get(c.territoryId).push(row);}
  }
  a.urbanized=add(a.urbanized,movedTotal);population.cohorts.sort((a,b)=>compare(a.id,b.id));require('./population.cjs').validatePopulationState(population,hierarchy);
  return require('./settlements.cjs').canonicalizeSettlements(next);
}
const stockQuantity=(enterprise,id)=>enterprise.inventories.find(s=>s.goodId===id).quantity;
function diagnostics(e,p,provinceId){
  const people=new Map(),paid=new Map(),firmsAt=new Map(),marketsAt=new Map(),recipes=new Map(e.recipes.map(r=>[r.id,r])),controllers=new Map((e.autonomy?.firms||[]).map(f=>[f.enterpriseId,f])),outputs=new Map(),sellable=new Map();
  for(const c of p.cohorts)people.set(c.territoryId,add(people.get(c.territoryId)||0,c.count));for(const m of e.markets){outputs.set(m.id,new Set());for(const id of m.provinceIds)marketsAt.set(id,m);}
  let workingCashRequired=0,cashHeldAgainstReserve=0,inhabitedRegions=0;for(const f of e.enterprises){paid.set(f.provinceId,add(paid.get(f.provinceId)||0,f.stats.workers));if(!firmsAt.has(f.provinceId))firmsAt.set(f.provinceId,[]);firmsAt.get(f.provinceId).push(f);outputs.get(marketsAt.get(f.provinceId).id).add(recipes.get(f.recipeId).output.goodId);const key=marketsAt.get(f.provinceId).id+':'+recipes.get(f.recipeId).output.goodId;sellable.set(key,add(sellable.get(key)||0,stockQuantity(f,recipes.get(f.recipeId).output.goodId)));if(e.autonomy){const reserve=workingReserve(e,f,recipes.get(f.recipeId),marketsAt.get(f.provinceId),controllers.get(f.id));workingCashRequired=add(workingCashRequired,reserve);cashHeldAgainstReserve=add(cashHeldAgainstReserve,Math.min(f.cashMinor,reserve));}}
  const required=new Set(),queue=[e.rules.foodGoodId];while(queue.length){const id=queue.pop();if(required.has(id))continue;required.add(id);for(const r of e.recipes)if(r.output.goodId===id)for(const input of r.inputs)queue.push(input.goodId);}
  const foodIds=new Set(e.rules.consumerNeeds.filter(n=>n.goodId===e.rules.foodGoodId&&n.usage==='consumable').map(n=>n.id)),result={householdSpending:0,regionsWithoutPaidLabor:0,populationWithoutPaidLabor:0,populationInRegionsWithUnmetFood:0,populationInRegionsWithUnaffordableFood:0,marketsWithMissingFoodStages:0,workingCashRequired,cashHeldAgainstReserve,naturalFoodConsumed:0,foodFeedbackEnabled:e.autonomy?.foodSecurity?.enabled||false,regionalWalletsAreAggregates:true,eventCountsAreOccurrences:true};
  for(const m of e.markets)if([...required].some(id=>!outputs.get(m.id).has(id)))result.marketsWithMissingFoodStages++;
  for(const h of e.households){const population=people.get(h.provinceId)||0;if(population)inhabitedRegions++;const food={need:0,affordableDemand:0,purchased:0,unaffordableNeed:0,rationedDemand:0,unmetNeed:0};for(const n of h.consumerState)if(foodIds.has(n.needId))for(const k of Object.keys(food))food[k]=add(food[k],n.stats[k]);result.householdSpending=add(result.householdSpending,h.stats.spending);if(!h.stats.wages&&population){result.regionsWithoutPaidLabor++;result.populationWithoutPaidLabor=add(result.populationWithoutPaidLabor,population);}if(food.unmetNeed)result.populationInRegionsWithUnmetFood=add(result.populationInRegionsWithUnmetFood,population);if(food.unaffordableNeed)result.populationInRegionsWithUnaffordableFood=add(result.populationInRegionsWithUnaffordableFood,population);
    if(h.provinceId===provinceId){const market=marketsAt.get(h.provinceId),local=firmsAt.get(h.provinceId)||[],reasons={},capitalGood=e.autonomy?.rules.capitalGoodId,capitalUnavailable=capitalGood&&!(sellable.get(market.id+':'+capitalGood)||0)&&local.some(f=>{const c=controllers.get(f.id);return c.pendingCapacity&&stockQuantity(f,capitalGood)<mul(c.pendingCapacity,e.autonomy.rules.capitalPerBatch);});for(const f of local){const reason=controllers.get(f.id)?.idleReason||'none';reasons[reason]=(reasons[reason]||0)+1;}result.region={provinceId,marketId:market.id,population,paidWorkers:paid.get(h.provinceId)||0,householdCash:h.cashMinor,wages:h.stats.wages,payout:h.stats.payout,spending:h.stats.spending,food,sellableFoodStock:sellable.get(market.id+':'+e.rules.foodGoodId)||0,sellableCapitalStock:capitalGood?sellable.get(market.id+':'+capitalGood)||0:0,foodPrice:market.goods.find(g=>g.goodId===e.rules.foodGoodId).priceMinor,missingMarketFoodStages:[...required].filter(id=>!outputs.get(market.id).has(id)).sort(compare),idleReasons:reasons,constraints:[...(food.unaffordableNeed?['purchasing-power']:[]),...(food.rationedDemand?['unfilled-paid-orders']:[]),...([...required].some(id=>!outputs.get(market.id).has(id))?['missing-local-chain']:[]),...(Object.hasOwn(reasons,'materials')?['enterprise-input-stocks']:[]),...(Object.hasOwn(reasons,'labor')?['local-labor']:[]),...(Object.hasOwn(reasons,'money')?['enterprise-cash']:[]),...(capitalUnavailable?['capital-unavailable']:[]),...((sellable.get(market.id+':'+e.rules.foodGoodId)||0)>0?['unsold-food-stock']:[])]};}
  }
  const total=[...people.values()].reduce((n,v)=>add(n,v),0);result.regionsWithoutPaidLaborBps=inhabitedRegions?number(BigInt(result.regionsWithoutPaidLabor)*10000n/BigInt(inhabitedRegions)):0;result.unmetFoodRegionPopulationBps=total?number(BigInt(result.populationInRegionsWithUnmetFood)*10000n/BigInt(total)):0;
  return result;
}
function report(state,provinceId){
  const e=state.systems.economy,p=state.systems.population,s=state.systems.settlements,a=e.autonomy,types={},industries={},reasons={},goods={},totals={urban:0,rural:0},recipes=new Map(e.recipes.map(r=>[r.id,r]));
  for(const c of p.cohorts)totals[c.settlement]=add(totals[c.settlement],c.count);
  let wages=0,revenue=0,profit=0,depreciation=0,cashFlow=0,capacity=0,batches=0,employment=0,payout=0,inventoryValue=0;
  for(const f of e.enterprises){const industry=recipes.get(f.recipeId).output.goodId;if(!industries[industry])industries[industry]={capacity:0,batches:0,produced:0,wages:0,revenue:0,profit:0,cogs:0};const row=industries[industry];for(const k of ['wages','revenue','cogs'])row[k]=add(row[k],f.stats[k]);row.profit=signedAdd(row.profit,f.stats.profit);row.capacity=add(row.capacity,f.capacityBatches);row.batches=add(row.batches,f.stats.batches);row.produced=add(row.produced,mul(f.stats.batches,recipes.get(f.recipeId).output.quantity));capacity=add(capacity,f.capacityBatches);batches=add(batches,f.stats.batches);wages=add(wages,f.stats.wages);revenue=add(revenue,f.stats.revenue);profit=signedAdd(profit,f.stats.profit);employment=add(employment,f.stats.workers);payout=add(payout,f.stats.payout);for(const stock of f.inventories)inventoryValue=add(inventoryValue,stock.bookValueMinor);}
  for(const f of a?.firms||[]){reasons[f.idleReason]=(reasons[f.idleReason]||0)+1;depreciation=add(depreciation,f.depreciation);cashFlow=signedAdd(cashFlow,f.cashFlow);}
  for(const row of s.rows)types[row.type]=(types[row.type]||0)+1;
  const needs=new Map(e.rules.consumerNeeds.map(n=>[n.id,n]));for(const b of e.stats.goods)goods[b.goodId]={...b,...(a?.goods.find(g=>g.goodId===b.goodId)||{}),need:0,householdPurchased:0,unaffordable:0,traded:0,shortage:0,surplus:0,priceMin:Number.MAX_SAFE_INTEGER,priceMax:0};
  for(const h of e.households)for(const n of h.consumerState){const g=goods[needs.get(n.needId).goodId];g.need=add(g.need,n.stats.need);g.householdPurchased=add(g.householdPurchased,n.stats.purchased);g.unaffordable=add(g.unaffordable,n.stats.unaffordableNeed);}
  for(const m of e.markets)for(const v of m.goods){const g=goods[v.goodId];g.traded=add(g.traded,v.stats.purchased);g.shortage=add(g.shortage,v.stats.shortage);g.surplus=add(g.surplus,v.stats.surplus);g.priceMin=Math.min(g.priceMin,v.priceMinor);g.priceMax=Math.max(g.priceMax,v.priceMinor);}
  const householdCash=e.households.reduce((n,h)=>add(n,h.cashMinor),0),enterpriseCash=e.enterprises.reduce((n,f)=>add(n,f.cashMinor),0),detail=diagnostics(e,p,provinceId);
  for(const id of Object.keys(goods)){const g=goods[id];g.inventory=g.closing;g.affordableDemand=g.need-g.unaffordable;g.rationedDemand=g.affordableDemand-g.householdPurchased;g.unmetNeed=g.need-g.householdPurchased;g.fulfillmentBps=g.need?number(BigInt(g.householdPurchased)*10000n/BigInt(g.need)):10000;}
  return {date:{...state.clock.date},population:add(totals.urban,totals.rural),...totals,births:p.stats.births,deaths:p.stats.deaths,urbanizationBps:number(BigInt(totals.urban)*10000n/BigInt(Math.max(1,totals.urban+totals.rural))),settlementTypes:types,largestCities:[...s.rows].filter(r=>r.classification==='urban').sort((a,b)=>b.population-a.population||compare(a.id,b.id)).slice(0,5).map(r=>({id:r.id,population:r.population})),enterprises:e.enterprises.length,active:e.enterprises.filter(f=>f.stats.batches>0).length,dormant:a?.firms.filter(f=>f.status==='dormant').length||0,pending:a?.firms.filter(f=>f.status==='pending').length||0,capacity,batches,employment,availableLabor:number(BigInt(totals.urban+totals.rural)*BigInt(e.rules.laborParticipationBps)/10000n),wages,investmentLabor:e.households.reduce((n,h)=>add(n,h.stats.wages),0)-wages,revenue,profit,operatingProfit:signedAdd(profit,-depreciation),depreciation,cashFlow,payout,inventoryValue,householdCash,enterpriseCash,cash:add(householdCash,enterpriseCash),capitalQuantity:(a?.firms||[]).reduce((n,f)=>add(n,f.capitalInUse.quantity),0),capitalValue:(a?.firms||[]).reduce((n,f)=>add(n,f.capitalInUse.bookValueMinor),0),urbanized:a?.urbanized||0,events:{...a?.events},idleReasons:reasons,industries,goods,diagnostics:detail,trade:{enabled:!!e.trade,quantity:e.trade?.month.quantity||0,goodsPayments:e.trade?.month.goodsPayments||0,freight:e.trade?.month.freight||0,workers:e.trade?.month.workers||0,edges:e.trade?.edges.length||0,householdInventory:(e.trade?.householdStocks||[]).reduce((n,s)=>add(n,s.quantity),0)}};
}
module.exports={defaults,enable,validate,begin,investmentOrders,finish,develop,report,record,workingReserve,foodEffects,configureFoodFeedback,number,add,mul,signedAdd};
