// Buyer-owned cargo advances at most one validated land edge per month.
const {add,mul,number,signedAdd}=require('./autonomous-economy.cjs');
const cmp=(a,b)=>a<b?-1:a>b?1:0;
const empty=()=>({started:0,delivered:0,quantity:0,goodsPayments:0,deliveredQuantity:0,freight:0,workers:0,byGood:{},byProvince:{},receipts:{},rejected:{price:0,cash:0,transport:0,route:0},routeEdges:0,deliveredFood:0});
function enable(e){if(e.trade&&!e.trade.routing)e.trade.routing={version:1,maxRouteEdges:12,freightPerWorkerMinor:8,nextId:1,cargo:[],month:empty()};}
function validate(e){
  const r=e.trade?.routing;if(!r)return;const fields=(o,k)=>{if(!o||Object.getPrototypeOf(o)!==Object.prototype||Object.keys(o).length!==k.length||k.some(v=>!Object.hasOwn(o,v)))throw Error('Routes: invalid fields');},safe=n=>Number.isSafeInteger(n)&&n>=0;
  fields(r,['version','maxRouteEdges','freightPerWorkerMinor','nextId','cargo','month']);fields(r.month,Object.keys(empty()));fields(r.month.rejected,['price','cash','transport','route']);if(r.version!==1||!safe(r.maxRouteEdges)||!r.maxRouteEdges||r.maxRouteEdges>64||!safe(r.freightPerWorkerMinor)||!r.freightPerWorkerMinor||!safe(r.nextId)||!r.nextId||Object.entries(r.month).some(([k,v])=>!['rejected','byGood','byProvince','receipts'].includes(k)&&!safe(v))||Object.values(r.month.rejected).some(v=>!safe(v)))throw Error('Routes: invalid rules');if(!r.month.byGood||Object.getPrototypeOf(r.month.byGood)!==Object.prototype||Object.entries(r.month.byGood).some(([k,v])=>!e.goods.some(g=>g.id===k)||!safe(v))||Object.values(r.month.byGood).reduce((n,v)=>add(n,v),0)!==r.month.quantity)throw Error('Routes: invalid goods aggregates');
  const provinces=new Set(e.households.map(h=>h.provinceId));if(!r.month.receipts||Object.getPrototypeOf(r.month.receipts)!==Object.prototype||Object.entries(r.month.receipts).some(([k,v])=>!provinces.has(k)||!safe(v))||Object.values(r.month.receipts).reduce((n,v)=>add(n,v),0)!==r.month.deliveredQuantity)throw Error('Routes: invalid receipts');if(!r.month.byProvince||Object.getPrototypeOf(r.month.byProvince)!==Object.prototype)throw Error('Routes: invalid carriers');let workers=0,freight=0;for(const [id,row]of Object.entries(r.month.byProvince)){fields(row,['workers','freight']);if(!provinces.has(id)||Object.values(row).some(v=>!safe(v)))throw Error('Routes: invalid carrier');workers=add(workers,row.workers);freight=add(freight,row.freight);}if(workers!==r.month.workers||freight!==r.month.freight)throw Error('Routes: inconsistent carrier totals');
  const markets=new Map(e.markets.map(m=>[m.id,m])),actors=new Map([...e.households,...e.enterprises].map(a=>[a.id,a])),edges=new Set(e.trade.edges.map(v=>v.a+'|'+v.b)),ids=new Set();
  for(const c of r.cargo){fields(c,['id','ownerId','sellerId','goodId','quantity','bookValueMinor','path','index','escrowMinor']);const owner=actors.get(c.ownerId),seller=actors.get(c.sellerId);if(!safe(c.id)||!c.id||c.id>=r.nextId||ids.has(c.id)||!owner||!seller?.recipeId||!e.goods.some(g=>g.id===c.goodId)||!safe(c.quantity)||!c.quantity||!safe(c.bookValueMinor)||!safe(c.escrowMinor)||!safe(c.index)||!Array.isArray(c.path)||c.path.length<3||c.path.length>r.maxRouteEdges+1||c.index<1||c.index>=c.path.length-1||new Set(c.path).size!==c.path.length||!markets.get(c.path[0])?.provinceIds.includes(seller.provinceId)||!markets.get(c.path.at(-1))?.provinceIds.includes(owner.provinceId)||!owner.recipeId&&c.goodId!==e.rules.foodGoodId)throw Error('Routes: invalid cargo');ids.add(c.id);for(let i=1;i<c.path.length;i++)if(!edges.has([c.path[i-1],c.path[i]].sort(cmp).join('|'))||markets.get(c.path[i]).accountingUnitId!==markets.get(c.path[0]).accountingUnitId)throw Error('Routes: invalid path');const remaining=c.path.length-1-c.index;if(c.escrowMinor!==mul(mul(Math.ceil(c.quantity/e.trade.rules.unitsPerWorker),r.freightPerWorkerMinor),remaining))throw Error('Routes: invalid freight escrow');}
}
function coordinate(e){
  const t=e.trade,r=t.routing,oldCargo=r.cargo;r.cargo=[];r.month=empty();t.flows=[];t.month={quantity:0,goodsPayments:0,freight:0,workers:0};
  const openingOffers=new Map(e.enterprises.map(f=>[f.id,f.inventories.find(s=>s.goodId===e.recipes.find(r=>r.id===f.recipeId).output.goodId).quantity]));
  const markets=new Map(e.markets.map(m=>[m.id,m])),at=new Map(e.markets.flatMap(m=>m.provinceIds.map(id=>[id,m.id]))),actors=new Map([...e.households,...e.enterprises].map(a=>[a.id,a])),houses=new Map(e.households.map(h=>[h.provinceId,h])),controllers=new Map(e.autonomy.firms.map(c=>[c.enterpriseId,c])),recipes=new Map(e.recipes.map(v=>[v.id,v])),heldFood=new Map(t.householdStocks.map(s=>[s.householdId,s])),labor=new Map(t.labor.map(l=>[l.provinceId,l])),edges=new Map(t.edges.map(v=>[v.a+'|'+v.b,v])),neighbors=new Map(e.markets.map(m=>[m.id,[]])),used=new Map();
  for(const edge of t.edges){neighbors.get(edge.a).push(edge.b);neighbors.get(edge.b).push(edge.a);}for(const list of neighbors.values())list.sort(cmp);
  const workerCount=q=>number((BigInt(q)+BigInt(t.rules.unitsPerWorker)-1n)/BigInt(t.rules.unitsPerWorker)),fee=q=>mul(workerCount(q),r.freightPerWorkerMinor),edgeKey=(a,b)=>[a,b].sort(cmp).join('|');
  function transport(path,index,q,good){const from=path[index],to=path[index+1],key=edgeKey(from,to),edge=edges.get(key),province=from===edge.a?edge.provinceA:edge.provinceB,l=labor.get(province),workers=workerCount(q);if(!l||l.remaining<workers||add(used.get(key)||0,q)>t.rules.capacityPerEdge)return false;l.remaining-=workers;used.set(key,add(used.get(key)||0,q));const carrier=houses.get(province),paid=fee(q);carrier.cashMinor=add(carrier.cashMinor,paid);carrier.stats.wages=add(carrier.stats.wages,paid);r.month.quantity=add(r.month.quantity,q);r.month.byGood[good]=add(r.month.byGood[good]||0,q);r.month.freight=add(r.month.freight,paid);r.month.workers=add(r.month.workers,workers);const row=r.month.byProvince[province]||{workers:0,freight:0};row.workers=add(row.workers,workers);row.freight=add(row.freight,paid);r.month.byProvince[province]=row;return true;}
  function deliver(c){const buyer=actors.get(c.ownerId),stock=buyer.recipeId?buyer.inventories.find(s=>s.goodId===c.goodId):heldFood.get(buyer.id);stock.quantity=add(stock.quantity,c.quantity);stock.bookValueMinor=add(stock.bookValueMinor,c.bookValueMinor);if(!buyer.recipeId)r.month.deliveredFood=add(r.month.deliveredFood,c.quantity);r.month.delivered=add(r.month.delivered,1);r.month.deliveredQuantity=add(r.month.deliveredQuantity,c.quantity);r.month.receipts[buyer.provinceId]=add(r.month.receipts[buyer.provinceId]||0,c.quantity);}
  // Earlier shipments have priority. No second edge or return to offers this month.
  for(const c of [...oldCargo].sort((a,b)=>a.id-b.id)){if(transport(c.path,c.index,c.quantity,c.goodId)){c.escrowMinor-=fee(c.quantity);c.bookValueMinor=add(c.bookValueMinor,fee(c.quantity));c.index++;if(c.index===c.path.length-1){deliver(c);continue;}}else r.month.rejected.transport++;r.cargo.push(c);}
  function paths(from){const result=new Map([[from,[from]]]),queue=[from],unit=markets.get(from).accountingUnitId;for(let i=0;i<queue.length;i++){const a=queue[i],path=result.get(a);if(path.length>r.maxRouteEdges)continue;for(const b of neighbors.get(a))if(!result.has(b)&&markets.get(b).accountingUnitId===unit){result.set(b,[...path,b]);queue.push(b);}}return result;}
  const offers=new Map(),buyers=new Map();const push=(map,key,value)=>{if(!map.has(key))map.set(key,[]);map.get(key).push(value);};
  const exported=new Set();const incoming=new Map();for(const c of r.cargo){const key=c.ownerId+'|'+c.goodId;incoming.set(key,add(incoming.get(key)||0,c.quantity));}
  for(const f of e.enterprises){const recipe=recipes.get(f.recipeId),c=controllers.get(f.id),stock=f.inventories.find(s=>s.goodId===recipe.output.goodId);if(openingOffers.get(f.id))push(offers,at.get(f.provinceId)+'|'+stock.goodId,{seller:f,stock,remaining:openingOffers.get(f.id)});
    for(const input of recipe.inputs){const stock=f.inventories.find(s=>s.goodId===input.goodId),q=c.status==='active'?Math.max(0,mul(mul(c.plannedBatches,e.autonomy.rules.inputReserveMonths),input.quantity)-stock.quantity-(incoming.get(f.id+'|'+input.goodId)||0)):0;if(q)push(buyers,input.goodId,{owner:f,remaining:q,reserve:mul(mul(c.plannedBatches,recipe.workersPerBatch),f.wagePerWorkerMinor),priority:1});}
    const good=e.autonomy.rules.capitalGoodId,held=f.inventories.find(s=>s.goodId===good),q=Math.max(0,mul(c.pendingCapacity,e.autonomy.rules.capitalPerBatch)-held.quantity-(incoming.get(f.id+'|'+good)||0));if(q&&c.status!=='dormant')push(buyers,good,{owner:f,remaining:q,reserve:add(require('./autonomous-economy.cjs').workingReserve(e,f,recipe,markets.get(at.get(f.provinceId)),c,false),e.autonomy.rules.organizationCostPerBatch),priority:2});
  }
  const natural=new Map((e.householdEconomy?.rows||[]).map(row=>[row.householdId,row.inventories.find(s=>s.goodId===e.rules.foodGoodId).quantity]));
  const ownProduction=new Map((e.householdEconomy?.rows||[]).map(row=>[row.householdId,row.ledger.find(b=>b.goodId===e.rules.foodGoodId).produced]));for(const h of e.households){const need=h.consumerState.filter(n=>e.rules.consumerNeeds.find(v=>v.id===n.needId).goodId===e.rules.foodGoodId).reduce((n,s)=>add(n,s.stats.need),0),foodNeed=Math.max(0,need-(ownProduction.get(h.id)||0)),holding=add(add(heldFood.get(h.id).quantity,incoming.get(h.id+'|'+e.rules.foodGoodId)||0),natural.get(h.id)||0);if(foodNeed)push(buyers,e.rules.foodGoodId,{owner:h,remaining:Math.max(0,foodNeed-holding),foodNeed,holding,reserve:0,priority:0});}
  // Only markets with a physical offer perform bounded BFS, once per month.
  const pathsAt=new Map(),candidates=[],best=new Map();for(const [key,list]of offers){const split=key.lastIndexOf('|'),from=key.slice(0,split),good=key.slice(split+1);if(!pathsAt.has(from))pathsAt.set(from,paths(from));for(const buyer of buyers.get(good)||[]){const to=at.get(buyer.owner.provinceId);if(from===to)continue;const path=pathsAt.get(from).get(to);if(!path){r.month.rejected.route++;continue;}const source=markets.get(from).goods.find(g=>g.goodId===good).priceMinor,ceiling=markets.get(to).goods.find(g=>g.goodId===good).priceMinor;const candidate={from,to,good,buyer,list,path,source,ceiling,benefit:ceiling-source},key=buyer.owner.id+'|'+good+'|'+buyer.priority;if(!best.has(key))best.set(key,[]);const choices=best.get(key);choices.push(candidate);choices.sort((a,b)=>cmp(BigInt(a.source)*BigInt(t.rules.unitsPerWorker)+BigInt(a.path.length-1)*BigInt(r.freightPerWorkerMinor),BigInt(b.source)*BigInt(t.rules.unitsPerWorker)+BigInt(b.path.length-1)*BigInt(r.freightPerWorkerMinor))||cmp(a.from,b.from));if(choices.length>3)choices.pop();}}
  candidates.push(...[...best.values()].flat());
  candidates.sort((a,b)=>a.buyer.priority-b.buyer.priority||b.benefit-a.benefit||cmp(a.from,b.from)||cmp(a.to,b.to)||cmp(a.good,b.good)||cmp(a.buyer.owner.id,b.buyer.owner.id));
  for(const c of candidates)for(const offer of c.list){const buyer=c.buyer;if(!buyer.owner.recipeId)buyer.remaining=Math.max(0,mul(buyer.foodNeed,c.path.length-1)-buyer.holding);if(!buyer.remaining||!offer.remaining)continue;const first=edges.get(edgeKey(c.from,c.path[1])),l=labor.get(c.from===first.a?first.provinceA:first.provinceB),capacity=t.rules.capacityPerEdge-(used.get(edgeKey(c.from,c.path[1]))||0);let q=Math.min(buyer.remaining,offer.remaining,offer.stock.quantity,capacity,l?mul(l.remaining,t.rules.unitsPerWorker):0);for(let i=1;i<c.path.length-1;i++){const edge=edges.get(edgeKey(c.path[i],c.path[i+1])),province=c.path[i]===edge.a?edge.provinceA:edge.provinceB,remaining=labor.get(province)?.remaining||0;q=Math.min(q,t.rules.capacityPerEdge,mul(remaining,t.rules.unitsPerWorker));}if(!q){r.month.rejected.transport++;continue;}const hops=c.path.length-1,budget=Math.max(0,buyer.owner.cashMinor-buyer.reserve);let lo=0,hi=q;while(lo<hi){const mid=lo+Math.ceil((hi-lo)/2),cost=BigInt(mid)*BigInt(c.source)+BigInt(fee(mid))*BigInt(hops);if(cost<=BigInt(budget))lo=mid;else hi=mid-1;}q=lo;if(!q){r.month.rejected.cash++;continue;}const payment=mul(q,c.source),freight=mul(fee(q),hops);if(BigInt(payment)+BigInt(freight)>=BigInt(q)*BigInt(c.ceiling)){r.month.rejected.price++;continue;}
    exported.add(offer.seller.id);const book=require('./economy-trade.cjs').take(offer.stock,q);buyer.owner.cashMinor-=add(payment,freight);offer.seller.cashMinor=add(offer.seller.cashMinor,payment);offer.seller.stats.revenue=add(offer.seller.stats.revenue,payment);offer.seller.stats.cogs=add(offer.seller.stats.cogs,book);offer.seller.stats.profit=offer.seller.stats.revenue-offer.seller.stats.cogs;const ctrl=controllers.get(offer.seller.id);ctrl.sold=add(ctrl.sold,q);const numerator=BigInt(ctrl.salesAverage)*BigInt(e.autonomy.rules.windowMonths)+BigInt(ctrl.salesRemainder)+BigInt(q);ctrl.salesAverage=number(numerator/BigInt(e.autonomy.rules.windowMonths));ctrl.salesRemainder=Number(numerator%BigInt(e.autonomy.rules.windowMonths));ctrl.profitTotal=signedAdd(ctrl.profitTotal,payment-book);ctrl.cashFlow=signedAdd(ctrl.cashFlow,payment);
    if(buyer.owner.recipeId){buyer.owner.stats.inputPurchases=add(buyer.owner.stats.inputPurchases,add(payment,freight));controllers.get(buyer.owner.id).cashFlow=signedAdd(controllers.get(buyer.owner.id).cashFlow,-add(payment,freight));}else{buyer.owner.stats.spending=add(buyer.owner.stats.spending,add(payment,freight));const need=buyer.owner.consumerState.find(s=>e.rules.consumerNeeds.find(n=>n.id===s.needId).goodId===e.rules.foodGoodId);need.stats.spending=add(need.stats.spending,add(payment,freight));}
    const cargo={id:r.nextId,ownerId:buyer.owner.id,sellerId:offer.seller.id,goodId:c.good,quantity:q,bookValueMinor:add(payment,fee(q)),path:c.path,index:1,escrowMinor:freight-fee(q)};r.nextId=add(r.nextId,1);transport(c.path,0,q,c.good);r.month.goodsPayments=add(r.month.goodsPayments,payment);buyer.remaining-=q;if(!buyer.owner.recipeId)buyer.holding=add(buyer.holding,q);offer.remaining-=q;r.month.started=add(r.month.started,1);r.month.routeEdges=add(r.month.routeEdges,hops);
    if(hops===1){deliver(cargo);if(!buyer.owner.recipeId)r.month.deliveredFood-=q;t.flows.push({from:c.from,to:c.to,sellerProvinceId:offer.seller.provinceId,buyerProvinceId:buyer.owner.provinceId,sellerEnterpriseId:offer.seller.id,buyerId:buyer.owner.id,goodId:c.good,quantity:q,payment,freight});for(const [k,v]of Object.entries({quantity:q,goodsPayments:payment,freight,workers:workerCount(q)}))t.month[k]=add(t.month[k],v);}else r.cargo.push(cargo);
  }
  return exported;
}
module.exports={enable,validate,coordinate,empty};
