// One land edge per month. Coordinator only; no global warehouse or credit.
const {number,add,mul}=require('./autonomous-economy.cjs');
const compare=(a,b)=>a<b?-1:a>b?1:0;
const fields=(o,keys)=>{if(!o||Object.getPrototypeOf(o)!==Object.prototype||Object.keys(o).length!==keys.length||keys.some(k=>!Object.hasOwn(o,k)))throw Error('Trade: invalid fields');};
const safe=n=>Number.isSafeInteger(n)&&n>=0;
function enable(state,adjacency,hierarchy){
  const next=structuredClone(state),e=next.systems.economy;if(!e?.autonomy||e.trade)throw Error('Trade: autonomy required, already enabled or absent');
  const land=require('./world-economy.cjs').validateAdjacency(adjacency,hierarchy),at=new Map(e.markets.flatMap(m=>m.provinceIds.map(id=>[id,m.id]))),edges=new Map();
  for(const [id,neighbors]of [...land].sort(([a],[b])=>compare(a,b)))for(const other of [...neighbors].sort(compare)){const a=at.get(id),b=at.get(other);if(!a||!b||a>=b)continue;const key=a+':'+b;if(!edges.has(key))edges.set(key,{a,b,provinceA:id,provinceB:other});}
  e.trade={version:1,rules:{capacityPerEdge:5000,unitsPerWorker:20,freightPerUnitMinor:1},edges:[...edges.values()].sort((x,y)=>compare(x.a,y.a)||compare(x.b,y.b)),householdStocks:e.households.map(h=>({householdId:h.id,quantity:0,bookValueMinor:0})),householdOpening:0,consumedImports:0,labor:[],flows:[],performance:[],month:{quantity:0,goodsPayments:0,freight:0,workers:0}};validate(e);return next;
}
function validate(e){
  if(!Object.hasOwn(e,'trade'))return;if(!e.autonomy)throw Error('Trade: autonomy required');const t=e.trade;fields(t,['version','rules','edges','householdStocks','householdOpening','consumedImports','labor','flows','performance','month',...(Object.hasOwn(t,'routing')?['routing']:[])]);fields(t.rules,['capacityPerEdge','unitsPerWorker','freightPerUnitMinor']);fields(t.month,['quantity','goodsPayments','freight','workers']);if(t.version!==1||!safe(t.householdOpening)||!safe(t.consumedImports)||Object.values(t.rules).some(v=>!safe(v)||!v)||Object.values(t.month).some(v=>!safe(v)))throw Error('Trade: invalid rules/statistics');
  const markets=new Map(e.markets.map(m=>[m.id,m])),houses=new Set(e.households.map(h=>h.id)),provinces=new Set(e.households.map(h=>h.provinceId)),seen=new Set();
  for(const edge of t.edges){fields(edge,['a','b','provinceA','provinceB']);const key=edge.a+':'+edge.b;if(!markets.has(edge.a)||!markets.has(edge.b)||edge.a>=edge.b||seen.has(key)||!markets.get(edge.a).provinceIds.includes(edge.provinceA)||!markets.get(edge.b).provinceIds.includes(edge.provinceB))throw Error('Trade: invalid edge');seen.add(key);}
  const actors=new Map([...e.enterprises,...e.households].map(a=>[a.id,a]));
  const edgeIds=new Set(t.edges.map(v=>v.a+':'+v.b));
  seen.clear();for(const s of t.householdStocks){fields(s,['householdId','quantity','bookValueMinor']);if(!houses.has(s.householdId)||seen.has(s.householdId)||!safe(s.quantity)||!safe(s.bookValueMinor)||!s.quantity&&s.bookValueMinor)throw Error('Trade: invalid owned stock');seen.add(s.householdId);}if(seen.size!==houses.size)throw Error('Trade: missing household stocks');
  seen.clear();for(const row of t.labor){fields(row,['provinceId','remaining']);if(!provinces.has(row.provinceId)||seen.has(row.provinceId)||!safe(row.remaining))throw Error('Trade: invalid labor');seen.add(row.provinceId);}
  seen.clear();const firms=new Set(e.enterprises.map(f=>f.id));for(const row of t.performance){fields(row,['enterpriseId','goodMonths',...(Object.hasOwn(row,'lossMonths')?['lossMonths']:[])]);if(!firms.has(row.enterpriseId)||seen.has(row.enterpriseId)||!safe(row.goodMonths)||Object.hasOwn(row,'lossMonths')&&!safe(row.lossMonths))throw Error('Trade: invalid performance history');seen.add(row.enterpriseId);}
  for(const f of t.flows){fields(f,['from','to','sellerProvinceId','buyerProvinceId','sellerEnterpriseId','buyerId','goodId','quantity','payment','freight']);if(!actors.get(f.sellerEnterpriseId)?.recipeId||actors.get(f.sellerEnterpriseId).provinceId!==f.sellerProvinceId||actors.get(f.buyerId)?.provinceId!==f.buyerProvinceId||!markets.has(f.from)||!markets.has(f.to)||!markets.get(f.from).provinceIds.includes(f.sellerProvinceId)||!markets.get(f.to).provinceIds.includes(f.buyerProvinceId)||houses.has(f.buyerId)&&f.goodId!==e.rules.foodGoodId||!e.goods.some(g=>g.id===f.goodId)||['quantity','payment','freight'].some(k=>!safe(f[k]))||!edgeIds.has([f.from,f.to].sort(compare).join(':')))throw Error('Trade: invalid flow');}
  const totals={quantity:0,goodsPayments:0,freight:0,workers:0},capacity=new Map();for(const f of t.flows){if(f.freight!==mul(f.quantity,t.rules.freightPerUnitMinor)&&(!t.routing||f.freight!==mul(Math.ceil(f.quantity/t.rules.unitsPerWorker),t.routing.freightPerWorkerMinor)))throw Error('Trade: invalid freight');for(const [key,value]of Object.entries({quantity:f.quantity,goodsPayments:f.payment,freight:f.freight,workers:Math.ceil(f.quantity/t.rules.unitsPerWorker)}))totals[key]=add(totals[key],value);const key=[f.from,f.to].sort(compare).join(':');capacity.set(key,add(capacity.get(key)||0,f.quantity));if(capacity.get(key)>t.rules.capacityPerEdge||markets.get(f.from).accountingUnitId!==markets.get(f.to).accountingUnitId)throw Error('Trade: invalid route capacity/unit');}if(Object.keys(totals).some(k=>totals[k]!==t.month[k]))throw Error('Trade: inconsistent totals');const held=t.householdStocks.reduce((n,s)=>add(n,s.quantity),0),received=t.flows.filter(f=>houses.has(f.buyerId)).reduce((n,f)=>add(n,f.quantity),0);if(BigInt(t.householdOpening)+BigInt(received)+BigInt(t.routing?.month.deliveredFood||0)-BigInt(t.consumedImports)!==BigInt(held))throw Error('Trade: inconsistent household goods balance');require('./economy-routes.cjs').validate(e);
}
function take(stock,q){const value=number(BigInt(stock.bookValueMinor)*BigInt(q)/BigInt(stock.quantity));stock.quantity-=q;stock.bookValueMinor-=value;return value;}
function transfer(from,to,value){from.cashMinor-=value;to.cashMinor=add(to.cashMinor,value);}
function coordinate(e){
  const t=e.trade;if(!t)return;const markets=new Map(e.markets.map(m=>[m.id,m])),marketAt=new Map(e.markets.flatMap(m=>m.provinceIds.map(id=>[id,m.id]))),recipes=new Map(e.recipes.map(r=>[r.id,r])),controllers=new Map(e.autonomy.firms.map(c=>[c.enterpriseId,c])),houseAt=new Map(e.households.map(h=>[h.provinceId,h])),stocks=new Map(t.householdStocks.map(s=>[s.householdId,s])),labor=new Map(t.labor.map(r=>[r.provinceId,r]));
  const routedExported=t.routing?require('./economy-routes.cjs').coordinate(e):null;
  if(!t.routing){
  t.flows=[];t.month={quantity:0,goodsPayments:0,freight:0,workers:0};const offers=new Map(),buyers=new Map();
  const bucket=(map,key)=>{if(!map.has(key))map.set(key,[]);return map.get(key);};
  // Freeze export quantities before receiving imports: a shipment cannot hop twice.
  for(const f of e.enterprises){const goodId=recipes.get(f.recipeId).output.goodId,s=f.inventories.find(s=>s.goodId===goodId);if(s.quantity)bucket(offers,marketAt.get(f.provinceId)+':'+goodId).push({f,s,remaining:s.quantity});
    for(const input of recipes.get(f.recipeId).inputs){const c=controllers.get(f.id),held=f.inventories.find(s=>s.goodId===input.goodId),quantity=c.status==='active'?Math.max(0,mul(mul(c.plannedBatches,e.autonomy.rules.inputReserveMonths),input.quantity)-held.quantity):0;if(quantity)bucket(buyers,marketAt.get(f.provinceId)+':'+input.goodId).push({owner:f,stock:held,remaining:quantity,payroll:mul(mul(c.plannedBatches,recipes.get(f.recipeId).workersPerBatch),f.wagePerWorkerMinor)});}}
  for(const f of e.enterprises){const c=controllers.get(f.id),good=e.autonomy.rules.capitalGoodId,held=f.inventories.find(s=>s.goodId===good),quantity=Math.max(0,mul(c.pendingCapacity,e.autonomy.rules.capitalPerBatch)-held.quantity);if(quantity&&c.status!=='dormant')bucket(buyers,marketAt.get(f.provinceId)+':'+good).push({owner:f,stock:held,remaining:quantity,payroll:add(require('./autonomous-economy.cjs').workingReserve(e,f,recipes.get(f.recipeId),markets.get(marketAt.get(f.provinceId)),c,false),mul(c.pendingCapacity,e.autonomy.rules.organizationCostPerBatch))});}
  for(const h of e.households){const s=stocks.get(h.id),quantity=h.consumerState.filter(n=>e.rules.consumerNeeds.find(v=>v.id===n.needId).goodId===e.rules.foodGoodId).reduce((v,n)=>add(v,n.stats.unmetNeed),0);if(quantity>s.quantity)bucket(buyers,marketAt.get(h.provinceId)+':'+e.rules.foodGoodId).unshift({owner:h,stock:s,remaining:quantity-s.quantity,payroll:0});}
  const candidates=[];for(const edge of t.edges)for(const [from,to,province]of [[edge.a,edge.b,edge.provinceA],[edge.b,edge.a,edge.provinceB]])for(const good of e.goods){if(markets.get(from).accountingUnitId!==markets.get(to).accountingUnitId)continue;const source=markets.get(from).goods.find(g=>g.goodId===good.id),destination=markets.get(to).goods.find(g=>g.goodId===good.id),benefit=destination.priceMinor-source.priceMinor-t.rules.freightPerUnitMinor;if(benefit>0)candidates.push({edge,from,to,province,goodId:good.id,benefit,price:source.priceMinor,ceiling:destination.priceMinor});}
  candidates.sort((a,b)=>b.benefit-a.benefit||compare(a.from,b.from)||compare(a.to,b.to)||compare(a.goodId,b.goodId));const used=new Map();
  for(const c of candidates){const route=c.edge.a+':'+c.edge.b,carrier=houseAt.get(c.province),available=labor.get(c.province);if(!available)continue;for(const buyer of buyers.get(c.to+':'+c.goodId)||[])for(const seller of offers.get(c.from+':'+c.goodId)||[]){
      if(!seller.remaining||!seller.s.quantity||!buyer.remaining)continue;const ask=Math.max(c.price,number((BigInt(seller.s.bookValueMinor)+BigInt(seller.s.quantity)-1n)/BigInt(seller.s.quantity||1))),delivered=add(ask,t.rules.freightPerUnitMinor);if(delivered>=c.ceiling||!seller.remaining||!buyer.remaining)continue;
      const q=Math.min(buyer.remaining,seller.remaining,seller.s.quantity,t.rules.capacityPerEdge-(used.get(route)||0),mul(available.remaining,t.rules.unitsPerWorker),number(BigInt(Math.max(0,buyer.owner.cashMinor-buyer.payroll))/BigInt(delivered)));if(!q)continue;
      const payment=mul(q,ask),freight=mul(q,t.rules.freightPerUnitMinor),workers=Math.ceil(q/t.rules.unitsPerWorker),book=take(seller.s,q);transfer(buyer.owner,seller.f,payment);transfer(buyer.owner,carrier,freight);carrier.stats.wages=add(carrier.stats.wages,freight);available.remaining-=workers;buyer.stock.quantity=add(buyer.stock.quantity,q);buyer.stock.bookValueMinor=add(buyer.stock.bookValueMinor,add(payment,freight));buyer.remaining-=q;seller.remaining-=q;used.set(route,add(used.get(route)||0,q));seller.f.stats.revenue=add(seller.f.stats.revenue,payment);seller.f.stats.cogs=add(seller.f.stats.cogs,book);seller.f.stats.profit=seller.f.stats.revenue-seller.f.stats.cogs;const controller=controllers.get(seller.f.id);controller.sold=add(controller.sold,q);const numerator=BigInt(controller.salesAverage)*BigInt(e.autonomy.rules.windowMonths)+BigInt(controller.salesRemainder)+BigInt(q);controller.salesAverage=number(numerator/BigInt(e.autonomy.rules.windowMonths));controller.salesRemainder=Number(numerator%BigInt(e.autonomy.rules.windowMonths));controller.profitTotal=require('./autonomous-economy.cjs').signedAdd(controller.profitTotal,payment-book);controller.cashFlow=require('./autonomous-economy.cjs').signedAdd(controller.cashFlow,payment);if(buyer.owner.recipeId){const control=controllers.get(buyer.owner.id);control.cashFlow=require('./autonomous-economy.cjs').signedAdd(control.cashFlow,-add(payment,freight));}if(buyer.owner.recipeId)buyer.owner.stats.inputPurchases=add(buyer.owner.stats.inputPurchases,add(payment,freight));else{buyer.owner.stats.spending=add(buyer.owner.stats.spending,add(payment,freight));const need=buyer.owner.consumerState.find(s=>e.rules.consumerNeeds.find(n=>n.id===s.needId).goodId===e.rules.foodGoodId);need.stats.spending=add(need.stats.spending,add(payment,freight));}t.flows.push({from:c.from,to:c.to,sellerProvinceId:seller.f.provinceId,buyerProvinceId:buyer.owner.provinceId,sellerEnterpriseId:seller.f.id,buyerId:buyer.owner.id,goodId:c.goodId,quantity:q,payment,freight});for(const [key,value]of Object.entries({quantity:q,goodsPayments:payment,freight,workers}))t.month[key]=add(t.month[key],value);
    }}
  }
  const performance=new Map(t.performance.map(p=>[p.enterpriseId,p])),exported=new Set([...t.flows.map(f=>f.sellerEnterpriseId),...(routedExported||[])]);for(const f of e.enterprises){const c=controllers.get(f.id),output=recipes.get(f.recipeId).output.quantity;let row=performance.get(f.id);if(!row){row={enterpriseId:f.id,goodMonths:0};t.performance.push(row);}row.lossMonths=f.stats.revenue>0&&f.stats.profit<0&&f.stats.batches>0?add(row.lossMonths||0,1):0;c.badMonths=Math.max(c.badMonths,row.lossMonths);if(row.lossMonths>=e.autonomy.rules.windowMonths)c.idleReason='unprofitable';if(c.status==='active'&&row.lossMonths>=e.autonomy.rules.closeMonths){c.status='dormant';c.cooldown=e.autonomy.rules.cooldownMonths;c.idleReason='closed';e.autonomy.events.closed=add(e.autonomy.events.closed,1);}
  row.goodMonths=exported.has(f.id)&&f.stats.profit>0&&f.stats.batches>0&&c.sold>=mul(f.stats.batches,output)?add(row.goodMonths,1):0;if(f.stats.profit>=0)c.badMonths=0;c.goodMonths=Math.max(c.goodMonths,row.goodMonths);if(c.goodMonths>=e.autonomy.rules.windowMonths&&!c.pendingCapacity&&!c.cooldown&&c.status==='active')c.pendingCapacity=Math.max(1,number(BigInt(f.capacityBatches)*BigInt(e.autonomy.rules.growthBps)/10000n));}
  // Export profits were realized after local payouts: distribute the remaining
  // current-month profit once, with the same real working/capital cash reserve.
  const incomeContext=e.householdEconomy?require('./household-economy.cjs').incomeContext(e):null;const owners=new Map(e.households.map(h=>[h.id,h]));for(const f of e.enterprises){if(e.householdEconomy){const payout=require('./household-economy.cjs').distribute(e,f,markets.get(marketAt.get(f.provinceId)),transfer,false,incomeContext);const c=controllers.get(f.id);c.cashFlow=require('./autonomous-economy.cjs').signedAdd(c.cashFlow,-payout);continue;}const c=controllers.get(f.id),desired=number(BigInt(Math.max(0,f.stats.profit))*BigInt(e.autonomy.rules.profitPayoutBps)/10000n),reserve=require('./autonomous-economy.cjs').workingReserve(e,f,recipes.get(f.recipeId),markets.get(marketAt.get(f.provinceId)),c),payout=Math.min(Math.max(0,desired-f.stats.payout),Math.max(0,f.cashMinor-reserve));if(payout){const owner=owners.get(f.ownerRef.id);transfer(f,owner,payout);f.stats.payout=add(f.stats.payout,payout);owner.stats.payout=add(owner.stats.payout,payout);c.cashFlow=require('./autonomous-economy.cjs').signedAdd(c.cashFlow,-payout);}}
  const balances=new Map(e.stats.goods.map(g=>[g.goodId,g]));for(const g of balances.values())g.closing=0;for(const f of e.enterprises)for(const s of f.inventories)balances.get(s.goodId).closing=add(balances.get(s.goodId).closing,s.quantity);for(const s of t.householdStocks)balances.get(e.rules.foodGoodId).closing=add(balances.get(e.rules.foodGoodId).closing,s.quantity);
  for(const row of e.householdEconomy?.rows||[])for(const s of row.inventories)balances.get(s.goodId).closing=add(balances.get(s.goodId).closing,s.quantity);for(const c of t.routing?.cargo||[])balances.get(c.goodId).closing=add(balances.get(c.goodId).closing,c.quantity);
  e.stats.cashAfter=number([...e.enterprises,...e.households].reduce((n,a)=>n+BigInt(a.cashMinor),0n)+(t.routing?.cargo||[]).reduce((n,c)=>n+BigInt(c.escrowMinor),0n));if(e.stats.cashAfter!==e.stats.cashBefore)throw Error('Trade: cash imbalance');
  validate(e);
}
module.exports={enable,validate,coordinate,take};
