// Small authoritative observation series; no economic decisions here.
const {add,number}=require('./autonomous-economy.cjs');
const keys=['year','month','population','foodNeed','foodConsumed','foodBps','batches','active','enterprises','workers','imports','freight'];
function analytics(state,{scope='world',id,after=0,offset=0,limit=20,detail=true}={}){
  if(typeof detail!=='boolean'||!Number.isSafeInteger(offset)||offset<0||!Number.isSafeInteger(limit)||limit<1||limit>100||!Number.isSafeInteger(after)||after<0)throw Error('Invalid analytics range');
  const e=state.systems.economy;if(!e)return {available:false,reason:'Экономика в этом сценарии не инициализирована.',monthly:[],annual:[]};
  if(scope==='country'&&!id)return {available:false,reason:'Выберите провинцию, принадлежащую государству.',monthly:[],annual:[]};
  if(!['world','country','province','market'].includes(scope))throw Error('Invalid economy scope');
  const market=e.markets.find(m=>m.id===id||scope==='province'&&m.provinceIds.includes(id)),ids=new Set(scope==='world'?e.households.map(h=>h.provinceId):scope==='country'?Object.keys(state.ownership).filter(p=>state.ownership[p]===id):scope==='market'?market?.provinceIds||[]:[id]),firms=e.enterprises.filter(f=>ids.has(f.provinceId)),houses=e.households.filter(h=>ids.has(h.provinceId));
  let population=0,foodNeed=0,foodConsumed=0,unaffordable=0,rationed=0,batches=0,workers=0;
  for(const c of state.systems.population.cohorts)if(ids.has(c.territoryId))population=add(population,c.count);
  const needs=new Set(e.rules.consumerNeeds?.filter(n=>n.goodId===e.rules.foodGoodId&&n.usage==='consumable').map(n=>n.id)||[]);
  for(const h of houses){const rows=e.rules.consumerNeeds?h.consumerState.filter(n=>needs.has(n.needId)).map(n=>n.stats):[{need:h.stats.essentialNeed,purchased:h.stats.purchased,unaffordableNeed:h.stats.unaffordableNeed,rationedDemand:h.stats.rationedDemand}];for(const n of rows){foodNeed=add(foodNeed,n.need);foodConsumed=add(foodConsumed,n.purchased);unaffordable=add(unaffordable,n.unaffordableNeed);rationed=add(rationed,n.rationedDemand);}}
  for(const f of firms){batches=add(batches,f.stats.batches);workers=add(workers,f.stats.workers);}
  const period=e.stats.lastCompletedPeriod||{year:state.clock.date.year,month:state.clock.date.month},point={...period,population,foodNeed,foodConsumed,foodBps:foodNeed?number(BigInt(foodConsumed)*10000n/BigInt(foodNeed)):0,batches,active:firms.filter(f=>f.stats.batches>0).length,enterprises:firms.length,workers,imports:(e.trade?.flows||[]).filter(f=>ids.has(f.buyerProvinceId)).reduce((n,f)=>add(n,f.quantity),0),freight:(e.trade?.flows||[]).filter(f=>ids.has(f.buyerProvinceId)).reduce((n,f)=>add(n,f.freight),0)};
  const attention=[];if(foodNeed&&point.foodBps<9000)attention.push({kind:'food',text:`Не обеспечено ${Math.round((10000-point.foodBps)/100)}% потребности в продовольствии`,provinceId:houses.find(h=>h.consumerState?h.consumerState.some(n=>needs.has(n.needId)&&n.stats.unmetNeed>0):h.stats.unmetNeed>0)?.provinceId});if(rationed)attention.push({kind:'supply',text:'Часть заявок на продовольствие остаётся без поставки',provinceId:houses.find(h=>h.consumerState?h.consumerState.some(n=>needs.has(n.needId)&&n.stats.rationedDemand>0):h.stats.rationedDemand>0)?.provinceId});if(unaffordable)attention.push({kind:'income',text:'Часть потребности не обеспечена денежным доходом',provinceId:houses.find(h=>h.consumerState?h.consumerState.some(n=>needs.has(n.needId)&&n.stats.unaffordableNeed>0):h.stats.unaffordableNeed>0)?.provinceId});
  const history=state.systems.economyHistory,recipes=new Map(e.recipes.map(r=>[r.id,r])),controllers=new Map((detail?e.autonomy?.firms||[]:[]).map(c=>[c.enterpriseId,c])),marketAt=new Map(detail?e.markets.flatMap(m=>m.provinceIds.map(id=>[id,m])):[]);
  return {available:true,autonomous:!!e.autonomy,completed:!!e.stats.lastCompletedPeriod,scope,id,point,monthly:scope==='world'?(history?.monthly||[]).filter(p=>p.year*12+p.month>after):[],annual:scope==='world'?(history?.annual||[]).filter(p=>p.year*12+p.month>after):[],attention:attention.slice(0,3),market:market?{id:market.id,prices:market.goods.map(g=>({goodId:g.goodId,price:g.priceMinor,shortage:g.stats.shortage,surplus:g.stats.surplus})),imports:(e.trade?.flows||[]).filter(f=>f.to===market.id),exports:(e.trade?.flows||[]).filter(f=>f.from===market.id)}:null,diagnostics:{unaffordable,rationed,householdCash:houses.reduce((n,h)=>add(n,h.cashMinor),0),enterpriseCash:firms.reduce((n,f)=>add(n,f.cashMinor),0),wages:houses.reduce((n,h)=>add(n,h.stats.wages),0),offset,limit,enterpriseCount:firms.length,stocks:(detail?firms.slice(offset,offset+limit):[]).map(f=>({id:f.id,stocks:f.inventories,profit:f.stats.profit,wage:f.wagePerWorkerMinor,productionCost:f.stats.productionCost,producedQuantity:number(BigInt(f.stats.batches)*BigInt(recipes.get(f.recipeId).output.quantity)),workingReserve:e.autonomy?require('./autonomous-economy.cjs').workingReserve(e,f,recipes.get(f.recipeId),marketAt.get(f.provinceId),controllers.get(f.id)):null,idle:controllers.get(f.id)?.idleReason})),trade:scope==='world'?e.trade?.month||null:null}};
}
function append(state,old){
  const point=analytics(state,{detail:false}).point,history=old?structuredClone(old):{version:1,monthly:[],annual:[]};history.monthly.push(point);history.monthly=history.monthly.slice(-120);
  let annual=history.annual.at(-1);if(!annual||annual.year!==point.year){annual={...point,months:0,totalBatches:0,totalFoodNeed:0,totalFoodConsumed:0,totalImports:0,totalFreight:0};history.annual.push(annual);}Object.assign(annual,point);annual.months++;for(const [key,source]of [['totalBatches','batches'],['totalFoodNeed','foodNeed'],['totalFoodConsumed','foodConsumed'],['totalImports','imports'],['totalFreight','freight']])annual[key]=add(annual[key],point[source]);history.annual=history.annual.slice(-200);validate(history);return history;
}
function validate(history){
  const fields=(o,k)=>{if(!o||Object.getPrototypeOf(o)!==Object.prototype||Object.keys(o).length!==k.length||k.some(v=>!Object.hasOwn(o,v)))throw Error('History: invalid fields');};fields(history,['version','monthly','annual']);if(history.version!==1||!Array.isArray(history.monthly)||!Array.isArray(history.annual)||history.monthly.length>120||history.annual.length>200)throw Error('History: invalid series');
  for(const [rows,annual]of [[history.monthly,false],[history.annual,true]]){let previous=-1;for(const row of rows){fields(row,annual?[...keys,'months','totalBatches','totalFoodNeed','totalFoodConsumed','totalImports','totalFreight']:keys);if(Object.values(row).some(v=>!Number.isSafeInteger(v)||v<0)||row.month<1||row.month>12||row.year<1700||row.year>9999||row.foodBps>10000||row.foodConsumed>row.foodNeed||row.foodBps!==(row.foodNeed?number(BigInt(row.foodConsumed)*10000n/BigInt(row.foodNeed)):0)||row.active>row.enterprises||annual&&(row.months<1||row.months>12))throw Error('History: invalid point');const n=annual?row.year:row.year*12+row.month;if(n<=previous)throw Error('History: unordered points');previous=n;}}
}
module.exports={analytics,append,validate};
