// Household workshops share the core's goods, recipes, labor and market clearing.
const {add,mul,number}=require('./autonomous-economy.cjs');
const safe=n=>Number.isSafeInteger(n)&&n>=0;
const fields=(o,k)=>{if(!o||Object.getPrototypeOf(o)!==Object.prototype||Object.keys(o).length!==k.length||k.some(v=>!Object.hasOwn(o,v)))throw Error('Household economy: invalid fields');};
const ledgerKeys=['opening','produced','inputs','consumed','bought','sold','closing'];
function enable(state){
  const next=structuredClone(state),e=next.systems.economy;if(!e?.autonomy||e.householdEconomy)throw Error('Household economy: autonomy required or already enabled');
  const controllers=new Map(e.autonomy.firms.map(c=>[c.enterpriseId,c]));
  const selected=[],visiting=new Set(),done=new Set();
  function visit(good){if(done.has(good))return;if(visiting.has(good))throw Error('Household economy: cyclic food method');visiting.add(good);const recipe=[...e.recipes].sort((a,b)=>a.id<b.id?-1:1).find(r=>r.output.goodId===good);if(!recipe)throw Error('Household economy: missing food method');for(const input of recipe.inputs)visit(input.goodId);selected.push(recipe);done.add(good);visiting.delete(good);}
  visit(e.rules.foodGoodId);
  const rural=new Map();for(const c of next.systems.population.cohorts)if(c.settlement==='rural')rural.set(c.territoryId,add(rural.get(c.territoryId)||0,c.count));
  const agriculture=new Set(next.systems.settlements.rows.filter(r=>r.classification==='rural'&&r.specializations.includes('agriculture')).map(r=>r.provinceId)),laborPerCycle=selected.reduce((n,r)=>add(n,r.workersPerBatch),0);
  e.householdEconomy={version:1,profitClaims:e.enterprises.map(f=>{const earned=Math.max(f.stats.payout,require('./autonomous-economy.cjs').signedAdd(f.stats.profit,-controllers.get(f.id).depreciation));return {enterpriseId:f.id,opening:0,earned,distributed:f.stats.payout,closing:Math.max(0,earned-f.stats.payout)};}),rows:e.households.map(h=>({householdId:h.id,stages:selected.map(r=>({recipeId:r.id,capacityBatches:agriculture.has(h.provinceId)?number(BigInt(rural.get(h.provinceId)||0)*BigInt(e.rules.laborParticipationBps)/10000n/BigInt(laborPerCycle)):0})),inventories:e.goods.map(g=>({goodId:g.id,quantity:0,bookValueMinor:0})),workers:0,revenue:0,spending:0,ledger:e.goods.map(g=>({goodId:g.id,...Object.fromEntries(ledgerKeys.map(k=>[k,0]))}))}))};validate(e);return next;
}
function validate(e){
  const extension=e.householdEconomy;if(!extension)return;fields(extension,['version','rows','profitClaims']);if(extension.version!==1||!e.autonomy||!Array.isArray(extension.rows))throw Error('Household economy: invalid version');
  const houses=new Set(e.households.map(h=>h.id)),goods=new Set(e.goods.map(g=>g.id)),recipes=new Set(e.recipes.map(r=>r.id)),recipeAt=new Map(e.recipes.map(r=>[r.id,r])),houseAt=new Map(e.households.map(h=>[h.id,h])),seen=new Set();
  for(const row of extension.rows){fields(row,['householdId','stages','inventories','workers','revenue','spending','ledger']);if(!houses.has(row.householdId)||seen.has(row.householdId)||['workers','revenue','spending'].some(k=>!safe(row[k])))throw Error('Household economy: invalid owner');seen.add(row.householdId);const stages=new Set();for(const s of row.stages){fields(s,['recipeId','capacityBatches']);if(!recipes.has(s.recipeId)||stages.has(s.recipeId)||!safe(s.capacityBatches))throw Error('Household economy: invalid capacity');stages.add(s.recipeId);}const held=new Set();for(const s of row.inventories){fields(s,['goodId','quantity','bookValueMinor']);if(!goods.has(s.goodId)||held.has(s.goodId)||!safe(s.quantity)||!safe(s.bookValueMinor)||!s.quantity&&s.bookValueMinor)throw Error('Household economy: invalid stock');held.add(s.goodId);}if(held.size!==goods.size)throw Error('Household economy: incomplete stocks');const balances=new Set();for(const b of row.ledger){fields(b,['goodId',...ledgerKeys]);if(!held.has(b.goodId)||balances.has(b.goodId)||ledgerKeys.some(k=>!safe(b[k]))||BigInt(b.opening)+BigInt(b.produced)+BigInt(b.bought)-BigInt(b.inputs)-BigInt(b.consumed)-BigInt(b.sold)!==BigInt(b.closing)||b.closing!==row.inventories.find(s=>s.goodId===b.goodId).quantity)throw Error('Household economy: invalid goods ledger');balances.add(b.goodId);}if(balances.size!==goods.size)throw Error('Household economy: incomplete ledger');const expectedInputs=new Map(),outputs=new Set();let expectedWorkers=0;for(const stage of row.stages){const recipe=recipeAt.get(stage.recipeId),produced=row.ledger.find(b=>b.goodId===recipe.output.goodId).produced;if(outputs.has(recipe.output.goodId)||produced%recipe.output.quantity||produced/recipe.output.quantity>stage.capacityBatches)throw Error('Household economy: invalid production method');outputs.add(recipe.output.goodId);const batches=produced/recipe.output.quantity;expectedWorkers=add(expectedWorkers,mul(batches,recipe.workersPerBatch));for(const input of recipe.inputs)expectedInputs.set(input.goodId,add(expectedInputs.get(input.goodId)||0,mul(batches,input.quantity)));}if(expectedWorkers!==row.workers||row.ledger.some(b=>b.inputs!==(expectedInputs.get(b.goodId)||0)||!outputs.has(b.goodId)&&b.produced||b.goodId!==e.rules.foodGoodId&&b.consumed))throw Error('Household economy: invalid production ledger');const consumed=houseAt.get(row.householdId).consumerState.filter(n=>e.rules.consumerNeeds.find(v=>v.id===n.needId).goodId===e.rules.foodGoodId).reduce((n,s)=>add(n,s.stats.purchased),0);if(row.ledger.find(b=>b.goodId===e.rules.foodGoodId).consumed>consumed)throw Error('Household economy: invalid consumption');}
  if(seen.size!==houses.size)throw Error('Household economy: missing owner');const firms=new Map(e.enterprises.map(f=>[f.id,f]));seen.clear();for(const c of extension.profitClaims){fields(c,['enterpriseId','opening','earned','distributed','closing']);const f=firms.get(c.enterpriseId);if(!f||seen.has(c.enterpriseId)||!safe(c.opening)||!safe(c.distributed)||!safe(c.closing)||!Number.isSafeInteger(c.earned)||BigInt(Math.max(0,require('./autonomous-economy.cjs').signedAdd(c.opening,c.earned)))-BigInt(c.distributed)!==BigInt(c.closing)||c.distributed!==f.stats.payout)throw Error('Household economy: invalid retained profit');seen.add(c.enterpriseId);}if(seen.size!==firms.size)throw Error('Household economy: missing retained profit');
}
function prepare(e,population,labor,balance,take){
  if(!e.householdEconomy)return;for(const c of e.householdEconomy.profitClaims){c.opening=c.closing;c.earned=0;c.distributed=0;}const rural=new Map(),mass=new Map(),houses=new Map(e.households.map(h=>[h.id,h])),recipes=new Map(e.recipes.map(r=>[r.id,r]));for(const c of population.cohorts){mass.set(c.territoryId,add(mass.get(c.territoryId)||0,c.count));if(c.settlement==='rural')rural.set(c.territoryId,add(rural.get(c.territoryId)||0,c.count));}
  for(const row of e.householdEconomy.rows){const h=houses.get(row.householdId),stocks=new Map(row.inventories.map(s=>[s.goodId,s])),opening=new Map(row.inventories.map(s=>[s.goodId,s.quantity])),previous=new Map(row.ledger.map(b=>[b.goodId,b.sold])),needs=new Map();
    row.workers=0;row.revenue=0;row.spending=0;for(const b of row.ledger)Object.assign(b,Object.fromEntries(ledgerKeys.map(k=>[k,k==='opening'||k==='closing'?stocks.get(b.goodId).quantity:0])));
    for(const n of e.rules.consumerNeeds)if(n.goodId===e.rules.foodGoodId&&n.usage==='consumable'){const s=h.consumerState.find(s=>s.needId===n.id);needs.set(n.goodId,add(needs.get(n.goodId)||0,number((BigInt(mass.get(h.provinceId)||0)*BigInt(n.perPersonNumerator)+BigInt(s.remainder))/BigInt(n.perPersonDenominator))));}
    // Propagate quantities through the selected data-defined method, never count grain as food.
    for(const stage of [...row.stages].reverse()){const r=recipes.get(stage.recipeId),target=add(needs.get(r.output.goodId)||0,previous.get(r.output.goodId)||0),batches=Math.ceil(target/r.output.quantity);for(const input of r.inputs)needs.set(input.goodId,add(needs.get(input.goodId)||0,mul(batches,input.quantity)));}
    let available=Math.min(labor.get(h.provinceId),number(BigInt(rural.get(h.provinceId)||0)*BigInt(e.rules.laborParticipationBps)/10000n));
    for(const stage of row.stages){const r=recipes.get(stage.recipeId),target=mul(add(needs.get(r.output.goodId)||0,previous.get(r.output.goodId)||0),2);let batches=Math.min(stage.capacityBatches,Math.floor(available/r.workersPerBatch),Math.max(0,Math.ceil((target-stocks.get(r.output.goodId).quantity)/r.output.quantity)));for(const input of r.inputs)batches=Math.min(batches,Math.floor(opening.get(input.goodId)/input.quantity));let book=0;for(const input of r.inputs){const q=mul(batches,input.quantity);if(q)book=add(book,take(stocks.get(input.goodId),q));opening.set(input.goodId,opening.get(input.goodId)-q);balance.get(input.goodId).inputsConsumed=add(balance.get(input.goodId).inputsConsumed,q);row.ledger.find(b=>b.goodId===input.goodId).inputs=add(row.ledger.find(b=>b.goodId===input.goodId).inputs,q);}const q=mul(batches,r.output.quantity),workers=mul(batches,r.workersPerBatch),out=stocks.get(r.output.goodId);out.quantity=add(out.quantity,q);out.bookValueMinor=add(out.bookValueMinor,book);balance.get(r.output.goodId).produced=add(balance.get(r.output.goodId).produced,q);row.ledger.find(b=>b.goodId===r.output.goodId).produced=add(row.ledger.find(b=>b.goodId===r.output.goodId).produced,q);available-=workers;labor.set(h.provinceId,labor.get(h.provinceId)-workers);row.workers=add(row.workers,workers);}
  }
}
function close(e){for(const row of e.householdEconomy?.rows||[])for(const b of row.ledger)b.closing=row.inventories.find(s=>s.goodId===b.goodId).quantity;}
function incomeContext(e){return {claims:new Map(e.householdEconomy.profitClaims.map(c=>[c.enterpriseId,c])),controls:new Map(e.autonomy.firms.map(c=>[c.enterpriseId,c])),recipes:new Map(e.recipes.map(r=>[r.id,r])),owners:new Map(e.households.map(h=>[h.id,h]))};}
function distribute(e,f,market,transfer,defer=false,context=incomeContext(e)){const a=require('./autonomous-economy.cjs'),c=context.claims.get(f.id),control=context.controls.get(f.id),recipe=context.recipes.get(f.recipeId);c.earned=a.signedAdd(f.stats.profit,-control.depreciation);const available=Math.max(0,a.signedAdd(c.opening,c.earned)),desired=number(BigInt(available)*BigInt(e.autonomy.rules.profitPayoutBps)/10000n),reserve=a.workingReserve(e,f,recipe,market,control),payout=defer?0:Math.min(Math.max(0,desired-c.distributed),Math.max(0,f.cashMinor-reserve));if(payout){const owner=context.owners.get(f.ownerRef.id);transfer(f,owner,payout);f.stats.payout=add(f.stats.payout,payout);owner.stats.payout=add(owner.stats.payout,payout);c.distributed=add(c.distributed,payout);}c.closing=Math.max(0,available-c.distributed);return payout;}
module.exports={enable,validate,prepare,close,distribute,incomeContext};
